//! Go HTTP REST SDK generator.

use super::HttpSdkGenerator;
use crate::generator::GeneratedFile;
use crate::unified::ir::{CommandIR, EngineIR, HttpEndpointIR, UnifiedIR};
use heck::{ToLowerCamelCase, ToPascalCase};
use std::fmt::Write;

pub struct GoHttpGenerator;

impl HttpSdkGenerator for GoHttpGenerator {
    fn language(&self) -> &'static str {
        "Go"
    }

    fn generate(&self, engine: &EngineIR, ir: &UnifiedIR) -> Vec<GeneratedFile> {
        let module = &ir.packages.go_module;
        let pascal = engine.name.to_pascal_case();
        vec![
            gen_go_mod(module),
            gen_errors(engine),
            gen_types(engine),
            gen_client(engine, &pascal),
            gen_readme(module, engine, &pascal),
            gen_agents(module, engine, &pascal),
        ]
    }
}

fn gen_go_mod(module: &str) -> GeneratedFile {
    GeneratedFile {
        path: "go.mod".into(),
        content: format!(
            "module {module}\n\n\
             go 1.21\n"
        ),
    }
}

fn gen_errors(engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("package main\n\nimport \"fmt\"\n\n");

    // Error code constants
    if !engine.error_codes.is_empty() {
        out.push_str("// Error codes returned by the API.\n");
        out.push_str("const (\n");
        for (code, def) in &engine.error_codes {
            writeln!(out, "\t// {} — {}", code, def.description).unwrap();
            writeln!(out, "\tErrorCode{} = \"{}\"", code.to_pascal_case(), code).unwrap();
        }
        out.push_str(")\n\n");
    }

    writeln!(
        out,
        "// {pascal}HttpError represents an error from the {pascal} HTTP API."
    )
    .unwrap();
    writeln!(out, "type {pascal}HttpError struct {{").unwrap();
    out.push_str("\tCode    string `json:\"code\"`\n");
    out.push_str("\tMessage string `json:\"message\"`\n");
    out.push_str("\tStatus  int    `json:\"status\"`\n");
    out.push_str("}\n\n");

    writeln!(
        out,
        "func (e *{pascal}HttpError) Error() string {{\n\
         \treturn fmt.Sprintf(\"%s %s\", e.Code, e.Message)\n\
         }}\n"
    )
    .unwrap();

    GeneratedFile {
        path: "errors.go".into(),
        content: out,
    }
}

fn gen_types(engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("package main\n\n");

    let mut has_types = false;
    for cmd in &engine.commands {
        if cmd.http.is_none() || cmd.response_fields.is_empty() {
            continue;
        }
        has_types = true;
        let type_name = format!("{pascal}{}Response", cmd.name.to_pascal_case());
        writeln!(
            out,
            "// {type_name} is the response for {name}.",
            name = cmd.name
        )
        .unwrap();
        writeln!(out, "type {type_name} struct {{").unwrap();
        for f in &cmd.response_fields {
            let go_type = match f.type_key.as_str() {
                "integer" => "int",
                "boolean" => "bool",
                "json" | "map" | "any" => "map[string]any",
                "array" => "[]any",
                _ => "string",
            };
            let json_tag = &f.name;
            let field_name = f.name.to_pascal_case();
            let type_str = if f.optional {
                format!("*{go_type}")
            } else {
                go_type.to_string()
            };
            let omit = if f.optional { ",omitempty" } else { "" };
            writeln!(out, "\t{field_name} {type_str} `json:\"{json_tag}{omit}\"`").unwrap();
        }
        out.push_str("}\n\n");
    }

    if !has_types {
        out.push_str("// No response types generated (no commands with HTTP endpoints and response fields).\n");
    }

    GeneratedFile {
        path: "types.go".into(),
        content: out,
    }
}

fn gen_client(engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("package main\n\n");
    out.push_str("import (\n");
    out.push_str("\t\"bytes\"\n");
    out.push_str("\t\"context\"\n");
    out.push_str("\t\"encoding/json\"\n");
    out.push_str("\t\"fmt\"\n");
    out.push_str("\t\"io\"\n");
    out.push_str("\t\"net/http\"\n");
    out.push_str("\t\"strings\"\n");
    out.push_str(")\n\n");

    writeln!(
        out,
        "// {pascal}Http is an HTTP REST client for the {pascal} API."
    )
    .unwrap();
    writeln!(out, "type {pascal}Http struct {{").unwrap();
    out.push_str("\tbaseURL string\n");
    out.push_str("\ttoken   string\n");
    out.push_str("\tclient  *http.Client\n");
    out.push_str("}\n\n");

    writeln!(
        out,
        "// New{pascal}Http creates a new {pascal} HTTP client."
    )
    .unwrap();
    writeln!(
        out,
        "func New{pascal}Http(baseURL, token string) *{pascal}Http {{"
    )
    .unwrap();
    writeln!(
        out,
        "\treturn &{pascal}Http{{\n\
         \t\tbaseURL: strings.TrimRight(baseURL, \"/\"),\n\
         \t\ttoken:   token,\n\
         \t\tclient:  &http.Client{{}},\n\
         \t}}\n\
         }}\n"
    )
    .unwrap();

    // Private request method
    writeln!(
        out,
        "func (c *{pascal}Http) request(ctx context.Context, method, path string, body any) ([]byte, error) {{"
    )
    .unwrap();
    out.push_str(
        r#"	url := c.baseURL + path
	var reqBody io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("marshal body: %w", err)
		}
		reqBody = bytes.NewReader(b)
	}
	req, err := http.NewRequestWithContext(ctx, method, url, reqBody)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}
	resp, err := c.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode >= 400 {
"#,
    );
    writeln!(
        out,
        "\t\tapiErr := &{pascal}HttpError{{Status: resp.StatusCode, Code: \"INTERNAL\"}}"
    )
    .unwrap();
    out.push_str(
        r#"		var errResp map[string]string
		if json.Unmarshal(data, &errResp) == nil {
			if v, ok := errResp["error"]; ok {
				apiErr.Code = v
			} else if v, ok := errResp["code"]; ok {
				apiErr.Code = v
			}
			if v, ok := errResp["message"]; ok {
				apiErr.Message = v
			} else if v, ok := errResp["detail"]; ok {
				apiErr.Message = v
			}
		}
		return nil, apiErr
	}
	return data, nil
}

"#,
    );

    // Generate methods
    for cmd in &engine.commands {
        let Some(http) = &cmd.http else { continue };
        gen_method(&mut out, cmd, http, engine, pascal);
    }

    GeneratedFile {
        path: "client.go".into(),
        content: out,
    }
}

fn gen_method(
    out: &mut String,
    cmd: &CommandIR,
    http: &HttpEndpointIR,
    _engine: &EngineIR,
    pascal: &str,
) {
    let method_name = cmd.name.to_pascal_case();
    let http_method = http.method.to_uppercase();

    let path_params = extract_path_params(&http.path);
    let has_body =
        matches!(http_method.as_str(), "POST" | "PATCH" | "DELETE") && http.body_type.is_some();

    // Return type
    let return_type = if cmd.response_fields.is_empty() {
        "map[string]any".to_string()
    } else {
        format!("*{pascal}{}Response", cmd.name.to_pascal_case())
    };

    // Build parameter list
    let mut params = vec!["ctx context.Context".to_string()];
    for pp in &path_params {
        params.push(format!("{} string", safe_go_name(pp)));
    }
    if has_body {
        params.push("body map[string]any".into());
    }
    let param_str = params.join(", ");

    writeln!(
        out,
        "// {method_name} — {} {} — {}",
        http.method, http.path, cmd.description
    )
    .unwrap();
    writeln!(
        out,
        "func (c *{pascal}Http) {method_name}({param_str}) ({return_type}, error) {{"
    )
    .unwrap();

    // Build path with fmt.Sprintf
    if path_params.is_empty() {
        let body_arg = if has_body { "body" } else { "nil" };
        writeln!(
            out,
            "\tdata, err := c.request(ctx, \"{http_method}\", \"{path}\", {body_arg})",
            path = http.path
        )
        .unwrap();
    } else {
        // Build fmt.Sprintf format string
        let mut fmt_path = http.path.clone();
        let mut fmt_args = Vec::new();
        for pp in &path_params {
            fmt_path = fmt_path.replace(&format!("{{{pp}}}"), "%s");
            fmt_args.push(safe_go_name(pp));
        }
        let body_arg = if has_body { "body" } else { "nil" };
        writeln!(
            out,
            "\tpath := fmt.Sprintf(\"{fmt_path}\", {})",
            fmt_args.join(", ")
        )
        .unwrap();
        writeln!(
            out,
            "\tdata, err := c.request(ctx, \"{http_method}\", path, {body_arg})"
        )
        .unwrap();
    }

    out.push_str("\tif err != nil {\n");
    out.push_str("\t\treturn nil, err\n");
    out.push_str("\t}\n");

    if cmd.response_fields.is_empty() {
        out.push_str("\tvar result map[string]any\n");
        out.push_str("\tif err := json.Unmarshal(data, &result); err != nil {\n");
        out.push_str("\t\treturn nil, fmt.Errorf(\"unmarshal response: %w\", err)\n");
        out.push_str("\t}\n");
        out.push_str("\treturn result, nil\n");
    } else {
        let resp_type = format!("{pascal}{}Response", cmd.name.to_pascal_case());
        writeln!(out, "\tvar result {resp_type}").unwrap();
        out.push_str("\tif err := json.Unmarshal(data, &result); err != nil {\n");
        out.push_str("\t\treturn nil, fmt.Errorf(\"unmarshal response: %w\", err)\n");
        out.push_str("\t}\n");
        out.push_str("\treturn &result, nil\n");
    }

    out.push_str("}\n\n");
}

fn extract_path_params(path: &str) -> Vec<String> {
    let mut params = Vec::new();
    let mut rest = path;
    while let Some(start) = rest.find('{') {
        if let Some(end) = rest[start..].find('}') {
            params.push(rest[start + 1..start + end].to_string());
            rest = &rest[start + end + 1..];
        } else {
            break;
        }
    }
    params
}

fn safe_go_name(name: &str) -> String {
    match name {
        "type" => "typ".into(),
        "json" => "jsonData".into(),
        "new" => "newValue".into(),
        "func" => "fn_".into(),
        "map" => "mapValue".into(),
        _ => name.to_lower_camel_case(),
    }
}

fn gen_readme(module: &str, engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    writeln!(out, "# {module}\n").unwrap();
    writeln!(
        out,
        "{pascal} HTTP REST SDK for ShrouDB (Go). Provides typed access to the {pascal} HTTP API \
         with zero external dependencies.\n"
    )
    .unwrap();

    out.push_str("## Installation\n\n");
    writeln!(out, "```bash\ngo get {module}\n```\n").unwrap();

    out.push_str("## Quick Start\n\n```go\n");
    writeln!(out, "import \"{module}\"\n").unwrap();
    writeln!(
        out,
        "{name} := New{pascal}Http(\"https://{name}.example.com:6500\", \"\")\n",
        name = engine.name
    )
    .unwrap();
    out.push_str("```\n\n");

    out.push_str("## Endpoints\n\n");
    out.push_str("| Method | Path | SDK Method | Description |\n");
    out.push_str("|--------|------|------------|-------------|\n");
    for cmd in &engine.commands {
        if let Some(http) = &cmd.http {
            let method_name = cmd.name.to_pascal_case();
            writeln!(
                out,
                "| `{}` | `{}` | `{method_name}()` | {} |",
                http.method, http.path, cmd.description
            )
            .unwrap();
        }
    }
    out.push('\n');

    GeneratedFile {
        path: "README.md".into(),
        content: out,
    }
}

fn gen_agents(module: &str, engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    writeln!(out, "# {pascal} HTTP SDK (Go) — Agent Instructions\n").unwrap();
    writeln!(
        out,
        "> HTTP REST client for {pascal}. Pure Go, zero external dependencies.\n"
    )
    .unwrap();

    out.push_str("## Quick Context\n\n");
    writeln!(out, "- **Module**: `{module}`").unwrap();
    out.push_str("- **Transport**: HTTP REST (net/http-based, no RESP3 dependency)\n");
    writeln!(
        out,
        "- **Pattern**: `{name}.Method(ctx, pathParams, body)` — all methods take context.Context",
        name = engine.name
    )
    .unwrap();
    out.push_str("- **Auth**: Bearer token via constructor\n\n");

    out.push_str("## Connection\n\n```go\n");
    writeln!(out, "import \"{module}\"\n").unwrap();
    writeln!(
        out,
        "{name} := New{pascal}Http(\"https://{name}.example.com:6500\", \"optional-bearer-token\")\n",
        name = engine.name
    )
    .unwrap();
    out.push_str("```\n\n");

    out.push_str("## Endpoints\n\n");
    out.push_str("| Method | Path | SDK Method | Description |\n");
    out.push_str("|--------|------|------------|-------------|\n");
    for cmd in &engine.commands {
        if let Some(http) = &cmd.http {
            let method_name = cmd.name.to_pascal_case();
            writeln!(
                out,
                "| `{}` | `{}` | `{method_name}()` | {} |",
                http.method, http.path, cmd.description
            )
            .unwrap();
        }
    }
    out.push('\n');

    GeneratedFile {
        path: "AGENTS.md".into(),
        content: out,
    }
}
