//! Python HTTP REST SDK generator.

use super::HttpSdkGenerator;
use crate::generator::GeneratedFile;
use crate::unified::ir::{CommandIR, EngineIR, HttpEndpointIR, UnifiedIR};
use heck::{ToPascalCase, ToSnakeCase};
use std::fmt::Write;

pub struct PyHttpGenerator;

impl HttpSdkGenerator for PyHttpGenerator {
    fn language(&self) -> &'static str {
        "Python"
    }

    fn generate(&self, engine: &EngineIR, ir: &UnifiedIR) -> Vec<GeneratedFile> {
        let pkg = &ir.packages.python;
        let pascal = engine.name.to_pascal_case();
        let pkg_dir = pkg.replace('-', "_");
        vec![
            gen_pyproject(pkg, &ir.version, engine),
            gen_init(&pkg_dir, &pascal),
            gen_errors(&pkg_dir, engine),
            gen_types(&pkg_dir, engine),
            gen_client(&pkg_dir, engine, &pascal),
            gen_readme(pkg, engine, &pascal),
            gen_agents(pkg, engine, &pascal),
        ]
    }
}

fn gen_pyproject(pkg: &str, version: &str, engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let pkg_dir = pkg.replace('-', "_");
    GeneratedFile {
        path: "pyproject.toml".into(),
        content: format!(
            r#"[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "{pkg}"
version = "{version}"
description = "ShrouDB {pascal} HTTP REST SDK"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"

[tool.setuptools.packages.find]
include = ["{pkg_dir}*"]
"#
        ),
    }
}

fn gen_init(pkg_dir: &str, pascal: &str) -> GeneratedFile {
    GeneratedFile {
        path: format!("{pkg_dir}/__init__.py"),
        content: format!(
            "# Auto-generated by shroudb-codegen. Do not edit.\n\n\
             from .client import {pascal}Http  # noqa: F401\n\
             from .errors import {pascal}HttpError  # noqa: F401\n"
        ),
    }
}

fn gen_errors(pkg_dir: &str, engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");

    writeln!(
        out,
        "class {pascal}HttpError(Exception):\n\
         \x20   \"\"\"Error returned by the {pascal} HTTP API.\"\"\"\n\n\
         \x20   def __init__(self, code: str, message: str, status: int) -> None:\n\
         \x20       super().__init__(f\"{{code}} {{message}}\")\n\
         \x20       self.code = code\n\
         \x20       self.message = message\n\
         \x20       self.status = status\n"
    )
    .unwrap();

    if !engine.error_codes.is_empty() {
        out.push_str("\n\n# Error codes\n");
        for (code, def) in &engine.error_codes {
            writeln!(out, "{code} = \"{code}\"  # {}", def.description).unwrap();
        }
    }

    GeneratedFile {
        path: format!("{pkg_dir}/errors.py"),
        content: out,
    }
}

fn gen_types(pkg_dir: &str, engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from typing import Any\n\n");

    for cmd in &engine.commands {
        if cmd.http.is_none() || cmd.response_fields.is_empty() {
            continue;
        }
        let type_name = format!("{pascal}{}Response", cmd.name.to_pascal_case());
        writeln!(out, "\n@dataclass").unwrap();
        writeln!(out, "class {type_name}:").unwrap();
        writeln!(out, "    \"\"\"Response for {}.\"\"\"", cmd.name).unwrap();
        for f in &cmd.response_fields {
            let py_type = match f.type_key.as_str() {
                "integer" => "int",
                "boolean" => "bool",
                "json" | "map" | "any" => "dict[str, Any]",
                "array" => "list[Any]",
                _ => "str",
            };
            let field_name = safe_py_name(&f.name);
            if f.optional {
                writeln!(out, "    {field_name}: {py_type} | None = None").unwrap();
            } else {
                writeln!(out, "    {field_name}: {py_type} = {}", py_default(py_type)).unwrap();
            }
        }
        out.push('\n');
    }

    GeneratedFile {
        path: format!("{pkg_dir}/types.py"),
        content: out,
    }
}

fn py_default(py_type: &str) -> &str {
    match py_type {
        "int" => "0",
        "bool" => "False",
        "dict[str, Any]" => "None  # type: ignore[assignment]",
        "list[Any]" => "None  # type: ignore[assignment]",
        _ => "\"\"",
    }
}

fn gen_client(pkg_dir: &str, engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("import json\n");
    out.push_str("import urllib.request\n");
    out.push_str("import urllib.error\n\n");
    writeln!(out, "from .errors import {pascal}HttpError").unwrap();
    out.push_str("from . import types\n\n\n");

    writeln!(out, "class {pascal}Http:").unwrap();
    writeln!(
        out,
        "    \"\"\"HTTP REST client for the {pascal} API.\"\"\"\n"
    )
    .unwrap();
    writeln!(
        out,
        "    def __init__(self, base_url: str, token: str | None = None) -> None:\n\
         \x20       self._base_url = base_url.rstrip(\"/\")\n\
         \x20       self._token = token\n"
    )
    .unwrap();

    // Private _request method
    writeln!(
        out,
        "    def _request(self, method: str, path: str, body: dict | None = None) -> dict:\n\
         \x20       url = f\"{{self._base_url}}{{path}}\"\n\
         \x20       data = json.dumps(body).encode() if body is not None else None\n\
         \x20       req = urllib.request.Request(url, data=data, method=method)\n\
         \x20       req.add_header(\"Content-Type\", \"application/json\")\n\
         \x20       if self._token:\n\
         \x20           req.add_header(\"Authorization\", f\"Bearer {{self._token}}\")\n\
         \x20       try:\n\
         \x20           with urllib.request.urlopen(req) as resp:\n\
         \x20               return json.loads(resp.read())\n\
         \x20       except urllib.error.HTTPError as exc:\n\
         \x20           code = \"INTERNAL\"\n\
         \x20           detail = \"\"\n\
         \x20           try:\n\
         \x20               err = json.loads(exc.read())\n\
         \x20               code = err.get(\"error\", err.get(\"code\", code))\n\
         \x20               detail = err.get(\"message\", err.get(\"detail\", \"\"))\n\
         \x20           except Exception:\n\
         \x20               detail = str(exc)\n\
         \x20           raise {pascal}HttpError(code, detail, exc.code) from exc\n"
    )
    .unwrap();

    // Generate methods
    for cmd in &engine.commands {
        let Some(http) = &cmd.http else { continue };
        out.push('\n');
        gen_method(&mut out, cmd, http, engine);
    }

    GeneratedFile {
        path: format!("{pkg_dir}/client.py"),
        content: out,
    }
}

fn gen_method(out: &mut String, cmd: &CommandIR, http: &HttpEndpointIR, engine: &EngineIR) {
    let method_name = cmd.name.to_snake_case();
    let http_method = http.method.to_uppercase();
    let pascal = engine.name.to_pascal_case();

    let path_params = extract_path_params(&http.path);
    let has_body =
        matches!(http_method.as_str(), "POST" | "PATCH" | "DELETE") && http.body_type.is_some();

    // Build parameter list
    let mut params = vec!["self".to_string()];
    for pp in &path_params {
        params.push(format!("{}: str", safe_py_name(pp)));
    }
    if has_body {
        params.push("body: dict".into());
    }
    let param_str = params.join(", ");

    // Return type
    let return_type = if cmd.response_fields.is_empty() {
        "dict".to_string()
    } else {
        format!("types.{pascal}{}Response", cmd.name.to_pascal_case())
    };

    writeln!(out, "    def {method_name}({param_str}) -> {return_type}:").unwrap();
    writeln!(out, "        \"\"\"{}\"\"\"", cmd.description).unwrap();

    // Build path with f-string substitution
    let mut py_path = http.path.clone();
    for pp in &path_params {
        py_path = py_path.replace(&format!("{{{pp}}}"), &format!("{{{}}}", safe_py_name(pp)));
    }

    if has_body {
        writeln!(
            out,
            "        resp = self._request(\"{http_method}\", f\"{py_path}\", body)"
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "        resp = self._request(\"{http_method}\", f\"{py_path}\")"
        )
        .unwrap();
    }

    if cmd.response_fields.is_empty() {
        writeln!(out, "        return resp").unwrap();
    } else {
        writeln!(out, "        return {return_type}(**resp)").unwrap();
    }
    out.push('\n');
}

fn extract_path_params(path: &str) -> Vec<String> {
    let mut params = Vec::new();
    let mut rest = path;
    while let Some(start) = rest.find('{') {
        if let Some(end) = rest[start..].find('}') {
            params.push(rest[start + 1..start + end].to_string());
            rest = &rest[start + end + 1..];
        } else {
            break;
        }
    }
    params
}

fn safe_py_name(name: &str) -> String {
    match name {
        "id" => "id_".into(),
        "json" => "json_data".into(),
        "type" => "type_".into(),
        "class" => "class_".into(),
        "import" => "import_".into(),
        "from" => "from_".into(),
        "global" => "global_".into(),
        _ => name.to_snake_case(),
    }
}

fn gen_readme(pkg: &str, engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    writeln!(out, "# {pkg}\n").unwrap();
    writeln!(
        out,
        "{pascal} HTTP REST SDK for ShrouDB (Python). Provides typed access to the {pascal} HTTP API \
         with zero external dependencies.\n"
    )
    .unwrap();

    out.push_str("## Installation\n\n");
    writeln!(out, "```bash\npip install {pkg}\n```\n").unwrap();

    out.push_str("## Quick Start\n\n```python\n");
    writeln!(
        out,
        "from {pkg_dir} import {pascal}Http\n\n\
         {name} = {pascal}Http(\"https://{name}.example.com:6500\")\n",
        pkg_dir = pkg.replace('-', "_"),
        name = engine.name
    )
    .unwrap();
    out.push_str("```\n\n");

    out.push_str("## Endpoints\n\n");
    out.push_str("| Method | Path | SDK Method | Description |\n");
    out.push_str("|--------|------|------------|-------------|\n");
    for cmd in &engine.commands {
        if let Some(http) = &cmd.http {
            let method_name = cmd.name.to_snake_case();
            writeln!(
                out,
                "| `{}` | `{}` | `{method_name}()` | {} |",
                http.method, http.path, cmd.description
            )
            .unwrap();
        }
    }
    out.push('\n');

    GeneratedFile {
        path: "README.md".into(),
        content: out,
    }
}

fn gen_agents(pkg: &str, engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    writeln!(out, "# {pascal} HTTP SDK (Python) — Agent Instructions\n").unwrap();
    writeln!(
        out,
        "> HTTP REST client for {pascal}. Pure Python, zero external dependencies.\n"
    )
    .unwrap();

    out.push_str("## Quick Context\n\n");
    writeln!(out, "- **Package**: `{pkg}`").unwrap();
    out.push_str("- **Transport**: HTTP REST (urllib-based, no RESP3 dependency)\n");
    writeln!(
        out,
        "- **Pattern**: `{name}.method(path_params, body)` — all methods synchronous",
        name = engine.name
    )
    .unwrap();
    out.push_str("- **Auth**: Bearer token via constructor\n\n");

    out.push_str("## Connection\n\n```python\n");
    writeln!(
        out,
        "from {pkg_dir} import {pascal}Http\n\n\
         {name} = {pascal}Http(\n    \"https://{name}.example.com:6500\",\n    token=\"optional-bearer-token\",\n)\n",
        pkg_dir = pkg.replace('-', "_"),
        name = engine.name
    )
    .unwrap();
    out.push_str("```\n\n");

    out.push_str("## Endpoints\n\n");
    out.push_str("| Method | Path | SDK Method | Description |\n");
    out.push_str("|--------|------|------------|-------------|\n");
    for cmd in &engine.commands {
        if let Some(http) = &cmd.http {
            let method_name = cmd.name.to_snake_case();
            writeln!(
                out,
                "| `{}` | `{}` | `{method_name}()` | {} |",
                http.method, http.path, cmd.description
            )
            .unwrap();
        }
    }
    out.push('\n');

    GeneratedFile {
        path: "AGENTS.md".into(),
        content: out,
    }
}
