//! Ruby HTTP REST SDK generator.

use super::HttpSdkGenerator;
use crate::generator::GeneratedFile;
use crate::unified::ir::{CommandIR, EngineIR, HttpEndpointIR, UnifiedIR};
use heck::{ToPascalCase, ToSnakeCase};
use std::fmt::Write;

pub struct RbHttpGenerator;

impl HttpSdkGenerator for RbHttpGenerator {
    fn language(&self) -> &'static str {
        "Ruby"
    }

    fn generate(&self, engine: &EngineIR, ir: &UnifiedIR) -> Vec<GeneratedFile> {
        let gem = &ir.packages.ruby;
        let pascal = engine.name.to_pascal_case();
        let gem_dir = gem.replace('-', "_");
        vec![
            gen_gemspec(gem, &ir.version, engine),
            gen_lib_root(gem, &gem_dir, &pascal),
            gen_errors(&gem_dir, engine),
            gen_types(&gem_dir, engine),
            gen_client(&gem_dir, engine, &pascal),
            gen_readme(gem, engine, &pascal),
            gen_agents(gem, engine, &pascal),
        ]
    }
}

fn gen_gemspec(gem: &str, version: &str, engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    GeneratedFile {
        path: format!("{gem}.gemspec"),
        content: format!(
            r##"# frozen_string_literal: true

Gem::Specification.new do |s|
  s.name        = "{gem}"
  s.version     = "{version}"
  s.summary     = "ShrouDB {pascal} HTTP REST SDK"
  s.description = "Pure Ruby HTTP client for the ShrouDB {pascal} API. Zero external dependencies."
  s.license     = "MIT"
  s.authors     = ["ShrouDB"]
  s.homepage    = "https://github.com/shroudb/shroudb-sdk-{name}-http-ruby"
  s.required_ruby_version = ">= 3.0"
  s.files       = Dir["lib/**/*.rb"]
end
"##,
            name = engine.name,
        ),
    }
}

fn gen_lib_root(_gem: &str, gem_dir: &str, _pascal: &str) -> GeneratedFile {
    GeneratedFile {
        path: format!("lib/{gem_dir}.rb"),
        content: format!(
            "# frozen_string_literal: true\n\
             # Auto-generated by shroudb-codegen. Do not edit.\n\n\
             require_relative \"{gem_dir}/errors\"\n\
             require_relative \"{gem_dir}/types\"\n\
             require_relative \"{gem_dir}/client\"\n",
        ),
    }
}

fn gen_errors(gem_dir: &str, engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();
    out.push_str("# frozen_string_literal: true\n");
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");

    writeln!(out, "module ShrouDB").unwrap();
    writeln!(out, "  # Error raised by the {pascal} HTTP client.").unwrap();
    writeln!(out, "  class {pascal}HttpError < StandardError").unwrap();
    out.push_str("    attr_reader :code, :detail, :status\n\n");
    out.push_str("    def initialize(code, detail, status)\n");
    // Ruby: super("#{code} #{detail}")
    out.push_str("      super(\"");
    out.push_str("#{code} #{detail}");
    out.push_str("\")\n");
    out.push_str("      @code = code\n");
    out.push_str("      @detail = detail\n");
    out.push_str("      @status = status\n");
    out.push_str("    end\n");
    out.push_str("  end\n");

    if !engine.error_codes.is_empty() {
        out.push_str("\n  # Error codes\n");
        out.push_str("  module ErrorCodes\n");
        for (code, def) in &engine.error_codes {
            writeln!(
                out,
                "    {} = \"{code}\".freeze # {}",
                code.to_snake_case().to_uppercase(),
                def.description
            )
            .unwrap();
        }
        out.push_str("  end\n");
    }

    out.push_str("end\n");

    GeneratedFile {
        path: format!("lib/{gem_dir}/errors.rb"),
        content: out,
    }
}

fn gen_types(gem_dir: &str, engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();
    out.push_str("# frozen_string_literal: true\n");
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");

    writeln!(out, "module ShrouDB").unwrap();

    for cmd in &engine.commands {
        if cmd.http.is_none() || cmd.response_fields.is_empty() {
            continue;
        }
        let type_name = format!("{pascal}{}Response", cmd.name.to_pascal_case());
        let field_names: Vec<String> = cmd
            .response_fields
            .iter()
            .map(|f| format!(":{}", f.name.to_snake_case()))
            .collect();
        writeln!(out, "  # Response for {}.", cmd.name).unwrap();
        writeln!(
            out,
            "  {type_name} = Struct.new({}, keyword_init: true)",
            field_names.join(", ")
        )
        .unwrap();
        out.push('\n');
    }

    out.push_str("end\n");

    GeneratedFile {
        path: format!("lib/{gem_dir}/types.rb"),
        content: out,
    }
}

fn gen_client(gem_dir: &str, engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("# frozen_string_literal: true\n");
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("require \"net/http\"\n");
    out.push_str("require \"json\"\n");
    out.push_str("require \"uri\"\n\n");

    writeln!(out, "module ShrouDB").unwrap();
    writeln!(out, "  # HTTP REST client for the {pascal} API.").unwrap();
    writeln!(out, "  class {pascal}Http").unwrap();

    // Constructor
    out.push_str("    # @param base_url [String] Base URL of the server.\n");
    out.push_str("    # @param token [String, nil] Bearer token for authentication.\n");
    out.push_str("    def initialize(base_url, token: nil)\n");
    out.push_str("      @base_url = base_url.chomp(\"/\")\n");
    out.push_str("      @token = token\n");
    out.push_str("    end\n\n");

    out.push_str("    private\n\n");

    // Private request method — use r##""## to avoid issues with Ruby string interpolation
    writeln!(out, "    def request(method, path, body = nil)").unwrap();
    out.push_str(
        r##"      uri = URI("#{@base_url}#{path}")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == "https"

      req = case method
            when "GET"    then Net::HTTP::Get.new(uri)
            when "POST"   then Net::HTTP::Post.new(uri)
            when "PATCH"  then Net::HTTP::Patch.new(uri)
            when "DELETE" then Net::HTTP::Delete.new(uri)
            else raise ArgumentError, "unsupported method: #{method}"
            end

      req["Content-Type"] = "application/json"
      req["Authorization"] = "Bearer #{@token}" if @token
      req.body = JSON.generate(body) if body

      resp = http.request(req)

      unless resp.is_a?(Net::HTTPSuccess)
        code = "INTERNAL"
        detail = ""
        begin
          err = JSON.parse(resp.body)
          code = err["error"] || err["code"] || code
          detail = err["message"] || err["detail"] || ""
        rescue JSON::ParserError
          detail = resp.body.to_s
        end
"##,
    );
    writeln!(
        out,
        "        raise {pascal}HttpError.new(code, detail, resp.code.to_i)"
    )
    .unwrap();
    out.push_str("      end\n\n");
    out.push_str("      JSON.parse(resp.body)\n");
    out.push_str("    end\n\n");

    out.push_str("    public\n\n");

    // Generate methods
    for cmd in &engine.commands {
        let Some(http) = &cmd.http else { continue };
        gen_method(&mut out, cmd, http, engine, pascal);
    }

    out.push_str("  end\n");
    out.push_str("end\n");

    GeneratedFile {
        path: format!("lib/{gem_dir}/client.rb"),
        content: out,
    }
}

fn gen_method(
    out: &mut String,
    cmd: &CommandIR,
    http: &HttpEndpointIR,
    _engine: &EngineIR,
    pascal: &str,
) {
    let method_name = cmd.name.to_snake_case();
    let http_method = http.method.to_uppercase();

    let path_params = extract_path_params(&http.path);
    let has_body =
        matches!(http_method.as_str(), "POST" | "PATCH" | "DELETE") && http.body_type.is_some();

    // Build parameter list
    let mut params = Vec::new();
    for pp in &path_params {
        params.push(pp.to_snake_case());
    }
    if has_body {
        params.push("body".into());
    }
    let param_str = if params.is_empty() {
        String::new()
    } else {
        format!("({})", params.join(", "))
    };

    writeln!(
        out,
        "    # {} {} — {}",
        http.method, http.path, cmd.description
    )
    .unwrap();
    writeln!(out, "    def {method_name}{param_str}").unwrap();

    // Build path with Ruby string interpolation
    // Use r##" to avoid Rust thinking #{...} is special
    let mut rb_path = http.path.clone();
    for pp in &path_params {
        let rb_var = pp.to_snake_case();
        // Replace {param} with Ruby interpolation
        rb_path = rb_path.replace(&format!("{{{pp}}}"), &format!("#{{{}}}", rb_var));
    }

    if has_body {
        writeln!(
            out,
            r##"      resp = request("{http_method}", "{rb_path}", body)"##
        )
        .unwrap();
    } else {
        writeln!(
            out,
            r##"      resp = request("{http_method}", "{rb_path}")"##
        )
        .unwrap();
    }

    // Return typed response or raw hash
    if cmd.response_fields.is_empty() {
        writeln!(out, "      resp").unwrap();
    } else {
        let type_name = format!("{pascal}{}Response", cmd.name.to_pascal_case());
        // Map response hash keys to snake_case Struct members
        let field_mappings: Vec<String> = cmd
            .response_fields
            .iter()
            .map(|f| {
                let rb_key = f.name.to_snake_case();
                format!(r##"{rb_key}: resp["{}"]"##, f.name)
            })
            .collect();
        writeln!(out, "      {type_name}.new({})", field_mappings.join(", ")).unwrap();
    }

    out.push_str("    end\n\n");
}

fn extract_path_params(path: &str) -> Vec<String> {
    let mut params = Vec::new();
    let mut rest = path;
    while let Some(start) = rest.find('{') {
        if let Some(end) = rest[start..].find('}') {
            params.push(rest[start + 1..start + end].to_string());
            rest = &rest[start + end + 1..];
        } else {
            break;
        }
    }
    params
}

fn gen_readme(gem: &str, engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    writeln!(out, "# {gem}\n").unwrap();
    writeln!(
        out,
        "{pascal} HTTP REST SDK for ShrouDB (Ruby). Provides typed access to the {pascal} HTTP API \
         with zero external dependencies.\n"
    )
    .unwrap();

    out.push_str("## Installation\n\n");
    writeln!(
        out,
        "```bash\ngem install {gem} --source https://rubygems.pkg.github.com/shroudb\n```\n"
    )
    .unwrap();

    let gem_dir = gem.replace('-', "_");
    out.push_str("## Quick Start\n\n```ruby\n");
    writeln!(out, r##"require "{gem_dir}""##).unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        r##"{name} = ShrouDB::{pascal}Http.new("https://{name}.example.com:6500")"##,
        name = engine.name
    )
    .unwrap();
    out.push_str("```\n\n");

    out.push_str("## Endpoints\n\n");
    out.push_str("| Method | Path | SDK Method | Description |\n");
    out.push_str("|--------|------|------------|-------------|\n");
    for cmd in &engine.commands {
        if let Some(http) = &cmd.http {
            let method_name = cmd.name.to_snake_case();
            writeln!(
                out,
                "| `{}` | `{}` | `{method_name}()` | {} |",
                http.method, http.path, cmd.description
            )
            .unwrap();
        }
    }
    out.push('\n');

    GeneratedFile {
        path: "README.md".into(),
        content: out,
    }
}

fn gen_agents(gem: &str, engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    writeln!(out, "# {pascal} HTTP SDK (Ruby) — Agent Instructions\n").unwrap();
    writeln!(
        out,
        "> HTTP REST client for {pascal}. Pure Ruby, zero external dependencies.\n"
    )
    .unwrap();

    let gem_dir = gem.replace('-', "_");
    out.push_str("## Quick Context\n\n");
    writeln!(out, "- **Gem**: `{gem}`").unwrap();
    out.push_str("- **Transport**: HTTP REST (Net::HTTP-based, no RESP3 dependency)\n");
    writeln!(
        out,
        "- **Pattern**: `{name}.method(path_params, body)` — all methods synchronous",
        name = engine.name
    )
    .unwrap();
    out.push_str("- **Auth**: Bearer token via constructor keyword\n\n");

    out.push_str("## Connection\n\n```ruby\n");
    writeln!(out, r##"require "{gem_dir}""##).unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        r##"{name} = ShrouDB::{pascal}Http.new("https://{name}.example.com:6500", token: "optional-bearer-token")"##,
        name = engine.name
    )
    .unwrap();
    out.push_str("```\n\n");

    out.push_str("## Endpoints\n\n");
    out.push_str("| Method | Path | SDK Method | Description |\n");
    out.push_str("|--------|------|------------|-------------|\n");
    for cmd in &engine.commands {
        if let Some(http) = &cmd.http {
            let method_name = cmd.name.to_snake_case();
            writeln!(
                out,
                "| `{}` | `{}` | `{method_name}()` | {} |",
                http.method, http.path, cmd.description
            )
            .unwrap();
        }
    }
    out.push('\n');

    GeneratedFile {
        path: "AGENTS.md".into(),
        content: out,
    }
}
