//! TypeScript HTTP REST SDK generator.

use super::HttpSdkGenerator;
use crate::generator::GeneratedFile;
use crate::unified::ir::{CommandIR, EngineIR, HttpEndpointIR, UnifiedIR};
use heck::{ToLowerCamelCase, ToPascalCase};
use std::fmt::Write;

pub struct TsHttpGenerator;

impl HttpSdkGenerator for TsHttpGenerator {
    fn language(&self) -> &'static str {
        "TypeScript"
    }

    fn generate(&self, engine: &EngineIR, ir: &UnifiedIR) -> Vec<GeneratedFile> {
        let pkg = &ir.packages.typescript;
        let pascal = engine.name.to_pascal_case();
        vec![
            gen_package_json(pkg, &ir.version, engine),
            gen_tsconfig(),
            gen_index(&pascal),
            gen_errors(engine),
            gen_types(engine),
            gen_client(engine, &pascal),
            gen_readme(pkg, engine, &pascal),
            gen_agents(pkg, engine, &pascal),
        ]
    }
}

fn gen_package_json(pkg: &str, version: &str, engine: &EngineIR) -> GeneratedFile {
    GeneratedFile {
        path: "package.json".into(),
        content: format!(
            r#"{{
  "name": "{pkg}",
  "version": "{version}",
  "description": "ShrouDB {pascal} HTTP REST SDK",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "exports": {{
    ".": {{
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js"
    }}
  }},
  "scripts": {{
    "build": "tsc",
    "prepublishOnly": "npm run build"
  }},
  "repository": {{
    "type": "git",
    "url": "https://github.com/shroudb/shroudb-sdk-{name}-http-typescript.git"
  }},
  "publishConfig": {{
    "registry": "https://npm.pkg.github.com"
  }},
  "license": "MIT",
  "engines": {{
    "node": ">=18"
  }},
  "devDependencies": {{
    "typescript": "^5"
  }}
}}
"#,
            pascal = engine.name.to_pascal_case(),
            name = engine.name,
        ),
    }
}

fn gen_tsconfig() -> GeneratedFile {
    GeneratedFile {
        path: "tsconfig.json".into(),
        content: r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "Node16",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "moduleResolution": "Node16",
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src"]
}
"#
        .into(),
    }
}

fn gen_index(pascal: &str) -> GeneratedFile {
    GeneratedFile {
        path: "src/index.ts".into(),
        content: format!(
            "// Auto-generated by shroudb-codegen. Do not edit.\n\n\
             export {{ {pascal}Http, type {pascal}HttpOptions }} from './client.js';\n\
             export {{ {pascal}HttpError }} from './errors.js';\n\
             export type * from './types.js';\n"
        ),
    }
}

fn gen_errors(engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");

    out.push_str("export const ErrorCode = {\n");
    for (code, def) in &engine.error_codes {
        writeln!(out, "  /** {desc} */", desc = def.description).unwrap();
        writeln!(out, "  {code}: \"{code}\",").unwrap();
    }
    out.push_str("} as const;\n\n");
    out.push_str("export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];\n\n");

    writeln!(
        out,
        "export class {pascal}HttpError extends Error {{\n\
         \x20 public readonly code: string;\n\
         \x20 public readonly status: number;\n\n\
         \x20 constructor(code: string, message: string, status: number) {{\n\
         \x20   super(`${{code}} ${{message}}`);\n\
         \x20   this.name = \"{pascal}HttpError\";\n\
         \x20   this.code = code;\n\
         \x20   this.status = status;\n\
         \x20 }}\n\
         }}"
    )
    .unwrap();

    GeneratedFile {
        path: "src/errors.ts".into(),
        content: out,
    }
}

fn gen_types(engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");

    for cmd in &engine.commands {
        if cmd.http.is_none() || cmd.response_fields.is_empty() {
            continue;
        }
        let type_name = format!("{pascal}{}Response", cmd.name.to_pascal_case());
        writeln!(out, "export interface {type_name} {{").unwrap();
        for f in &cmd.response_fields {
            let ts_type = match f.type_key.as_str() {
                "integer" => "number",
                "boolean" => "boolean",
                "json" | "map" | "any" => "Record<string, unknown>",
                "array" => "unknown[]",
                _ => "string",
            };
            let opt = if f.optional { "?" } else { "" };
            writeln!(out, "  {}{opt}: {ts_type};", f.name).unwrap();
        }
        out.push_str("}\n\n");
    }

    GeneratedFile {
        path: "src/types.ts".into(),
        content: out,
    }
}

fn gen_client(engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");
    writeln!(out, "import {{ {pascal}HttpError }} from './errors.js';").unwrap();
    out.push_str("import type * as types from './types.js';\n\n");

    writeln!(out, "export interface {pascal}HttpOptions {{").unwrap();
    out.push_str(
        "  /** Base URL of the Sigil HTTP server (e.g., \"https://sigil.example.com:6500\"). */\n",
    );
    out.push_str("  baseUrl: string;\n");
    out.push_str("  /** Bearer token for authentication. */\n");
    out.push_str("  token?: string;\n");
    out.push_str("}\n\n");

    writeln!(out, "export class {pascal}Http {{").unwrap();
    out.push_str("  private baseUrl: string;\n");
    out.push_str("  private token?: string;\n\n");

    writeln!(
        out,
        "  constructor(options: {pascal}HttpOptions) {{\n\
         \x20   this.baseUrl = options.baseUrl.replace(/\\/+$/, '');\n\
         \x20   this.token = options.token;\n\
         \x20 }}\n"
    )
    .unwrap();

    // Private request method
    out.push_str(
        r#"  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const url = `${this.baseUrl}${path}`;
    const headers: Record<string, string> = { 'Content-Type': 'application/json' };
    if (this.token) headers['Authorization'] = `Bearer ${this.token}`;
    const resp = await fetch(url, {
      method,
      headers,
      body: body != null ? JSON.stringify(body) : undefined,
    });
    if (!resp.ok) {
      let code = 'INTERNAL';
      let detail = '';
      try {
        const json = await resp.json() as Record<string, string>;
        code = json.error ?? json.code ?? code;
        detail = json.message ?? json.detail ?? '';
      } catch { detail = await resp.text(); }
"#,
    );
    writeln!(
        out,
        "      throw new {pascal}HttpError(code, detail, resp.status);"
    )
    .unwrap();
    out.push_str("    }\n");
    out.push_str("    return resp.json() as T;\n");
    out.push_str("  }\n");

    // Generate a method for each command with an HTTP endpoint
    for cmd in &engine.commands {
        let Some(http) = &cmd.http else { continue };
        out.push('\n');
        gen_method(&mut out, cmd, http, engine);
    }

    out.push_str("}\n");

    GeneratedFile {
        path: "src/client.ts".into(),
        content: out,
    }
}

fn gen_method(out: &mut String, cmd: &CommandIR, http: &HttpEndpointIR, _engine: &EngineIR) {
    let method_name = cmd.name.to_lower_camel_case();
    let http_method = http.method.to_uppercase();
    let return_type = if cmd.response_fields.is_empty() {
        "Record<string, unknown>".to_string()
    } else {
        format!(
            "types.{}{}Response",
            _engine.name.to_pascal_case(),
            cmd.name.to_pascal_case()
        )
    };

    // Extract path parameters from URL template: {schema}, {id}, {name}, etc.
    let path_params: Vec<String> = extract_path_params(&http.path);

    // Build function parameters
    let mut params = Vec::new();
    for pp in &path_params {
        params.push(format!("{}: string", safe_ts_name(pp)));
    }

    // For POST/PATCH/DELETE with a body, add a body parameter
    let has_body =
        matches!(http_method.as_str(), "POST" | "PATCH" | "DELETE") && http.body_type.is_some();
    if has_body {
        params.push("body: Record<string, unknown>".into());
    }

    let param_str = params.join(", ");

    writeln!(
        out,
        "  /** {} {} — {} */",
        http.method, http.path, cmd.description
    )
    .unwrap();
    writeln!(
        out,
        "  async {method_name}({param_str}): Promise<{return_type}> {{"
    )
    .unwrap();

    // Build the path with template substitution
    let mut ts_path = http.path.clone();
    for pp in &path_params {
        ts_path = ts_path.replace(&format!("{{{pp}}}"), &format!("${{{}}}", safe_ts_name(pp)));
    }

    if has_body {
        writeln!(
            out,
            "    return this.request('{http_method}', `{ts_path}`, body);"
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "    return this.request('{http_method}', `{ts_path}`);"
        )
        .unwrap();
    }

    out.push_str("  }\n");
}

fn extract_path_params(path: &str) -> Vec<String> {
    let mut params = Vec::new();
    let mut rest = path;
    while let Some(start) = rest.find('{') {
        if let Some(end) = rest[start..].find('}') {
            params.push(rest[start + 1..start + end].to_string());
            rest = &rest[start + end + 1..];
        } else {
            break;
        }
    }
    params
}

fn safe_ts_name(name: &str) -> String {
    match name {
        "new" => "newValue".into(),
        "delete" => "deleteFlag".into(),
        "class" => "className".into(),
        _ => name.into(),
    }
}

fn gen_readme(pkg: &str, engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    writeln!(out, "# {pkg}\n").unwrap();
    writeln!(
        out,
        "{pascal} HTTP REST SDK for ShrouDB. Provides typed access to the {pascal} HTTP API \
         for frontend applications — login, signup, password management, JWT verification.\n"
    )
    .unwrap();

    out.push_str("## Installation\n\n");
    out.push_str("Configure the GitHub Packages npm registry (one-time setup):\n\n");
    out.push_str(
        "```bash\necho \"@shroudb:registry=https://npm.pkg.github.com\" >> .npmrc\n```\n\n",
    );
    out.push_str("Then install:\n\n");
    writeln!(out, "```bash\nnpm install {pkg}\n```\n").unwrap();

    out.push_str("## Quick Start\n\n```typescript\n");
    writeln!(out, "import {{ {pascal}Http }} from '{pkg}';\n").unwrap();
    writeln!(
        out,
        "const {name} = new {pascal}Http({{ baseUrl: 'https://{name}.example.com:6500' }});\n",
        name = engine.name
    )
    .unwrap();
    out.push_str("```\n\n");

    out.push_str("## Endpoints\n\n");
    out.push_str("| Method | Path | SDK Method | Description |\n");
    out.push_str("|--------|------|------------|-------------|\n");
    for cmd in &engine.commands {
        if let Some(http) = &cmd.http {
            let method_name = cmd.name.to_lower_camel_case();
            writeln!(
                out,
                "| `{}` | `{}` | `{method_name}()` | {} |",
                http.method, http.path, cmd.description
            )
            .unwrap();
        }
    }
    out.push('\n');

    GeneratedFile {
        path: "README.md".into(),
        content: out,
    }
}

fn gen_agents(pkg: &str, engine: &EngineIR, pascal: &str) -> GeneratedFile {
    let mut out = String::new();
    writeln!(out, "# {pascal} HTTP SDK — Agent Instructions\n").unwrap();
    writeln!(
        out,
        "> HTTP REST client for {pascal}. Use this for frontend integration — login, signup, \
         password management, JWT verification.\n"
    )
    .unwrap();

    out.push_str("## Quick Context\n\n");
    writeln!(out, "- **Package**: `{pkg}`").unwrap();
    out.push_str("- **Transport**: HTTP REST (fetch-based, no RESP3 dependency)\n");
    writeln!(
        out,
        "- **Pattern**: `{name}.method(pathParams, body)` — all methods async",
        name = engine.name
    )
    .unwrap();
    out.push_str("- **Auth**: Bearer token via constructor options\n\n");

    out.push_str("## Connection\n\n```typescript\n");
    writeln!(out, "import {{ {pascal}Http }} from '{pkg}';\n").unwrap();
    writeln!(
        out,
        "const {name} = new {pascal}Http({{\n  baseUrl: 'https://{name}.example.com:6500',\n  token: 'optional-bearer-token',\n}});\n",
        name = engine.name
    ).unwrap();
    out.push_str("```\n\n");

    out.push_str("## Endpoints\n\n");
    out.push_str("| Method | Path | SDK Method | Description |\n");
    out.push_str("|--------|------|------------|-------------|\n");
    for cmd in &engine.commands {
        if let Some(http) = &cmd.http {
            let method_name = cmd.name.to_lower_camel_case();
            writeln!(
                out,
                "| `{}` | `{}` | `{method_name}()` | {} |",
                http.method, http.path, cmd.description
            )
            .unwrap();
        }
    }
    out.push('\n');

    GeneratedFile {
        path: "AGENTS.md".into(),
        content: out,
    }
}
