//! ShrouDB unified client class generation for Python.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use heck::ToPascalCase;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_client(ir)]
}

fn gen_client(ir: &UnifiedIR) -> GeneratedFile {
    let pkg = &ir.packages.python;
    let mut out = String::new();

    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from typing import Any\n\n");
    out.push_str("from ._transport._interface import Transport\n");
    out.push_str("from ._transport._http import HttpTransport\n");
    out.push_str("from ._transport._resp3 import Resp3Transport, MoatResp3Transport\n");

    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        writeln!(
            out,
            "from .engines.{name} import {pascal}Namespace",
            name = engine.name
        )
        .unwrap();
    }

    out.push('\n');

    // _NoTransport helper.
    out.push_str(
        r#"
class _NoTransport(Transport):
    """Placeholder transport that raises on any call."""

    def __init__(self, engine: str) -> None:
        self._engine = engine

    async def execute(self, engine: str, args: list[str]) -> dict[str, Any]:
        raise RuntimeError(
            f"No transport configured for {self._engine}. "
            f"Provide a moat URL or {self._engine} URI."
        )

    async def close(self) -> None:
        pass

"#,
    );

    // ShrouDB class.
    out.push_str(
        r#"
class ShrouDB:
    """ShrouDB unified client.

    Provides namespaced access to all ShrouDB engines. Each engine is
    accessible as a property (e.g., ``db.cipher.encrypt(...)``).

    Supply a ``moat`` URL to route all engines through a Moat gateway,
    or individual engine URIs for direct connections.
    """

"#,
    );

    // Constructor.
    out.push_str("    def __init__(\n");
    out.push_str("        self,\n");
    out.push_str("        *,\n");
    out.push_str("        moat: str | None = None,\n");
    out.push_str("        token: str | None = None,\n");
    for engine in &ir.engines {
        writeln!(
            out,
            "        {name}: str | None = None,",
            name = engine.name
        )
        .unwrap();
    }
    out.push_str("    ) -> None:\n");

    out.push_str("        self._transports: list[Transport] = []\n\n");

    // Resolve default transport from moat URI.
    out.push_str("        default_transport: Transport | None = None\n");
    out.push_str("        if moat is not None:\n");
    out.push_str("            if moat.startswith(\"http://\") or moat.startswith(\"https://\"):\n");
    out.push_str("                prefixes: dict[str, str] = {\n");
    for engine in &ir.engines {
        writeln!(
            out,
            "                    \"{name}\": \"{prefix}\",",
            name = engine.name,
            prefix = engine.http_prefix
        )
        .unwrap();
    }
    out.push_str("                }\n");
    out.push_str("                default_transport = HttpTransport(moat, token, prefixes)\n");
    out.push_str("            else:\n");
    out.push_str("                default_transport = MoatResp3Transport(moat)\n");
    out.push_str("            self._transports.append(default_transport)\n\n");

    // Per-engine transport resolution.
    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        let name = &engine.name;

        writeln!(out, "        if {name} is not None:").unwrap();
        writeln!(out, "            _t_{name} = Resp3Transport({name})").unwrap();
        writeln!(out, "            self._transports.append(_t_{name})").unwrap();
        writeln!(
            out,
            "            self.{name}: {pascal}Namespace = {pascal}Namespace(_t_{name}, \"{name}\")"
        )
        .unwrap();
        writeln!(out, "        elif default_transport is not None:").unwrap();
        writeln!(
            out,
            "            self.{name} = {pascal}Namespace(default_transport, \"{name}\")"
        )
        .unwrap();
        writeln!(out, "        else:").unwrap();
        writeln!(
            out,
            "            self.{name} = {pascal}Namespace(_NoTransport(\"{name}\"), \"{name}\")"
        )
        .unwrap();
        out.push('\n');
    }

    // close()
    out.push_str(
        r#"    async def close(self) -> None:
        """Close all connections and release resources."""
        for transport in self._transports:
            await transport.close()

    async def __aenter__(self) -> ShrouDB:
        return self

    async def __aexit__(self, *exc: object) -> None:
        await self.close()
"#,
    );

    GeneratedFile {
        path: format!("{pkg}/client.py"),
        content: out,
    }
}
