//! Per-engine namespace class generation for Python.

use crate::generator::GeneratedFile;
use crate::unified::ir::{CommandIR, EngineIR, UnifiedIR};
use heck::{ToPascalCase, ToSnakeCase};
use std::fmt::Write;

use super::types::resolve_py_type;

/// Escape Python reserved words used as parameter names.
fn py_safe_name(name: &str) -> String {
    let snake = name.to_snake_case();
    match snake.as_str() {
        "from" => "from_".into(),
        "import" => "import_".into(),
        "class" => "class_".into(),
        "return" => "return_".into(),
        "global" => "global_".into(),
        "lambda" => "lambda_".into(),
        "pass" => "pass_".into(),
        "del" => "del_".into(),
        "in" => "in_".into(),
        "is" => "is_".into(),
        "not" => "not_".into(),
        "and" => "and_".into(),
        "or" => "or_".into(),
        // Shadowing built-in modules/functions
        "json" => "json_data".into(),
        "type" => "type_".into(),
        "id" => "id_".into(),
        "list" => "list_".into(),
        "dict" => "dict_".into(),
        "str" => "str_".into(),
        "int" => "int_".into(),
        "hash" => "hash_".into(),
        _ => snake,
    }
}

pub(super) fn generate(ir: &UnifiedIR, engine: &EngineIR) -> Vec<GeneratedFile> {
    let pkg = &ir.packages.python;
    let mut files = vec![gen_engine_namespace(pkg, engine)];
    files.push(gen_engines_init(pkg, ir));
    files
}

fn gen_engines_init(pkg: &str, ir: &UnifiedIR) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n");

    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        writeln!(
            out,
            "from .{name} import {pascal}Namespace  # noqa: F401",
            name = engine.name
        )
        .unwrap();
    }

    GeneratedFile {
        path: format!("{pkg}/engines/__init__.py"),
        content: out,
    }
}

fn gen_engine_namespace(pkg: &str, engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();

    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("import base64\n");
    out.push_str("import json\n");
    out.push_str("from typing import Any\n\n");
    out.push_str("from .._transport._interface import Transport\n");

    // Import response types if any command has response fields.
    let has_types = engine
        .commands
        .iter()
        .any(|c| !c.response_fields.is_empty());
    if has_types {
        writeln!(
            out,
            "from ..types import {name} as _types",
            name = engine.name
        )
        .unwrap();
    }
    out.push('\n');

    writeln!(out, "\nclass {pascal}Namespace:").unwrap();
    writeln!(
        out,
        "    \"\"\"{pascal} — {desc}\"\"\"\n",
        desc = engine.description
    )
    .unwrap();

    writeln!(
        out,
        "    def __init__(self, transport: Transport, engine: str = \"{name}\") -> None:",
        name = engine.name
    )
    .unwrap();
    out.push_str("        self._transport = transport\n");
    out.push_str("        self._engine = engine\n");

    for cmd in &engine.commands {
        out.push('\n');
        gen_command_method(&mut out, engine, cmd);
        if cmd.batchable {
            out.push('\n');
            gen_batch_method(&mut out, engine, cmd);
        }
    }

    GeneratedFile {
        path: format!("{pkg}/engines/{}.py", engine.name),
        content: out,
    }
}

fn gen_command_method(out: &mut String, engine: &EngineIR, cmd: &CommandIR) {
    // PIPELINE is a unique wire shape (nested RESP3 sub-command arrays + optional
    // REQUEST_ID). The generic flat-args emitter can't express it; generate a
    // dedicated method that delegates to transport.execute_pipeline.
    if cmd.verb == "PIPELINE" && cmd.subcommand.is_none() {
        gen_pipeline_method(out, cmd);
        return;
    }

    let method_name = cmd.name.to_snake_case();

    // Build parameter list.
    let mut params = vec!["self".to_string()];
    for p in &cmd.positional_params {
        let py_type = if engine.is_base64_type(&p.type_key) {
            "str | bytes".to_string()
        } else {
            resolve_py_type(engine, &p.type_key)
        };
        if p.required {
            params.push(format!("{}: {py_type}", py_safe_name(&p.name)));
        } else {
            params.push(format!(
                "{}: {py_type} | None = None",
                py_safe_name(&p.name)
            ));
        }
    }

    // Named params become keyword arguments.
    for p in &cmd.named_params {
        let py_type = resolve_py_type(engine, &p.type_key);
        if p.type_key == "boolean" {
            params.push(format!("{}: bool = False", py_safe_name(&p.name)));
        } else {
            params.push(format!(
                "{}: {py_type} | None = None",
                py_safe_name(&p.name)
            ));
        }
    }

    let param_str = params.join(", ");

    // Return type.
    let return_type = if cmd.response_fields.is_empty() {
        "dict[str, Any]".to_string()
    } else {
        format!(
            "_types.{}{}Response",
            engine.name.to_pascal_case(),
            cmd.name.to_pascal_case()
        )
    };

    // Docstring.
    let verb_display = match &cmd.subcommand {
        Some(sub) => format!("{} {}", cmd.verb, sub),
        None => cmd.verb.clone(),
    };

    writeln!(
        out,
        "    async def {method_name}({param_str}) -> {return_type}:"
    )
    .unwrap();
    writeln!(
        out,
        "        \"\"\"{verb_display} — {}\"\"\"",
        cmd.description
    )
    .unwrap();

    // Build the RESP3 args array.
    write!(out, "        args: list[str] = [\"{}\"", cmd.verb).unwrap();
    if let Some(sub) = &cmd.subcommand {
        write!(out, ", \"{sub}\"").unwrap();
    }
    out.push_str("]\n");

    // Append positional params.
    for p in &cmd.positional_params {
        let snake = py_safe_name(&p.name);
        if !p.required {
            writeln!(out, "        if {snake} is not None:").unwrap();
            if p.type_key == "json" {
                writeln!(
                    out,
                    "            args.append({snake} if isinstance({snake}, str) else json.dumps({snake}))"
                )
                .unwrap();
            } else {
                writeln!(out, "            args.append(str({snake}))").unwrap();
            }
        } else {
            // Required branch: may carry a wire-keyword prefix
            // (e.g. `CA CREATE <name> <algorithm> SUBJECT <subject>`).
            if let Some(k) = &p.wire_key {
                writeln!(out, "        args.append(\"{k}\")").unwrap();
            }
            if p.type_key == "json" {
                writeln!(
                    out,
                    "        args.append({snake} if isinstance({snake}, str) else json.dumps({snake}))"
                )
                .unwrap();
            } else if engine.is_base64_type(&p.type_key) {
                // Auto-encode bytes to base64; pass strings through (assumed already encoded).
                writeln!(
                    out,
                    "        args.append({snake} if isinstance({snake}, str) else base64.b64encode({snake}).decode())"
                )
                .unwrap();
            } else {
                writeln!(out, "        args.append(str({snake}))").unwrap();
            }
        }
    }

    // Append named (keyword) params.
    for p in &cmd.named_params {
        let snake = py_safe_name(&p.name);
        let default_key = p.name.to_uppercase();
        let wire_key = p.wire_key.as_deref().unwrap_or(&default_key);
        if p.type_key == "boolean" {
            writeln!(out, "        if {snake}:").unwrap();
            writeln!(out, "            args.append(\"{wire_key}\")").unwrap();
        } else if p.type_key == "json" {
            writeln!(out, "        if {snake} is not None:").unwrap();
            writeln!(out, "            args.append(\"{wire_key}\")").unwrap();
            writeln!(
                out,
                "            args.append({snake} if isinstance({snake}, str) else json.dumps({snake}))"
            )
            .unwrap();
        } else {
            writeln!(out, "        if {snake} is not None:").unwrap();
            writeln!(out, "            args.append(\"{wire_key}\")").unwrap();
            writeln!(out, "            args.append(str({snake}))").unwrap();
        }
    }

    // Execute and return.
    writeln!(
        out,
        "        result = await self._transport.execute(self._engine, args)"
    )
    .unwrap();

    if cmd.response_fields.is_empty() {
        writeln!(out, "        return result").unwrap();
    } else {
        let type_name = format!(
            "_types.{}{}Response",
            engine.name.to_pascal_case(),
            cmd.name.to_pascal_case()
        );
        let field_args: Vec<String> = cmd
            .response_fields
            .iter()
            .map(|f| {
                let default = if f.optional {
                    String::new()
                } else {
                    format!(", {}", py_zero_value(&f.type_key))
                };
                format!("{}=result.get(\"{}\"{})", f.name, f.name, default)
            })
            .collect();
        if field_args.len() > 2 {
            writeln!(out, "        return {type_name}(").unwrap();
            for arg in &field_args {
                writeln!(out, "            {arg},").unwrap();
            }
            writeln!(out, "        )").unwrap();
        } else {
            writeln!(
                out,
                "        return {type_name}({args})",
                args = field_args.join(", ")
            )
            .unwrap();
        }
    }
}

fn gen_pipeline_method(out: &mut String, cmd: &CommandIR) {
    writeln!(
        out,
        "    async def pipeline(\n        self,\n        commands: list[list[str]],\n        request_id: str | None = None,\n    ) -> list[dict[str, Any]]:"
    )
    .unwrap();
    writeln!(
        out,
        "        \"\"\"PIPELINE — {desc}\"\"\"",
        desc = cmd.description
    )
    .unwrap();
    writeln!(
        out,
        "        return await self._transport.execute_pipeline(self._engine, commands, request_id)"
    )
    .unwrap();
}

fn gen_batch_method(out: &mut String, engine: &EngineIR, cmd: &CommandIR) {
    let method_name = format!("{base}_many", base = cmd.name.to_snake_case());

    writeln!(out, "    async def {method_name}(").unwrap();
    out.push_str("        self,\n");
    out.push_str("        calls: list[dict[str, Any]],\n");

    let item_return_type = if cmd.response_fields.is_empty() {
        "list[dict[str, Any]]".to_string()
    } else {
        format!(
            "list[_types.{}{}Response]",
            engine.name.to_pascal_case(),
            cmd.name.to_pascal_case()
        )
    };
    writeln!(out, "    ) -> {item_return_type}:").unwrap();
    writeln!(
        out,
        "        \"\"\"{verb} — batch variant: pipelines N independent calls over one connection (ordered, not atomic).\"\"\"",
        verb = cmd.verb,
    )
    .unwrap();
    out.push_str("        args_list: list[list[str]] = []\n");
    out.push_str("        for call in calls:\n");
    out.push_str("            args: list[str] = [");
    write!(out, "\"{}\"", cmd.verb).unwrap();
    if let Some(sub) = &cmd.subcommand {
        write!(out, ", \"{sub}\"").unwrap();
    }
    out.push_str("]\n");

    for p in &cmd.positional_params {
        let key = py_safe_name(&p.name);
        let accessor = format!("call[\"{key}\"]");
        if p.required {
            if let Some(k) = &p.wire_key {
                writeln!(out, "            args.append(\"{k}\")").unwrap();
            }
            if p.type_key == "json" {
                writeln!(
                    out,
                    "            args.append({accessor} if isinstance({accessor}, str) else json.dumps({accessor}))"
                )
                .unwrap();
            } else if engine.is_base64_type(&p.type_key) {
                writeln!(
                    out,
                    "            args.append({accessor} if isinstance({accessor}, str) else base64.b64encode({accessor}).decode())"
                )
                .unwrap();
            } else {
                writeln!(out, "            args.append(str({accessor}))").unwrap();
            }
        } else {
            writeln!(out, "            if \"{key}\" in call:").unwrap();
            if p.type_key == "json" {
                writeln!(
                    out,
                    "                args.append({accessor} if isinstance({accessor}, str) else json.dumps({accessor}))"
                )
                .unwrap();
            } else {
                writeln!(out, "                args.append(str({accessor}))").unwrap();
            }
        }
    }

    for p in &cmd.named_params {
        let name_upper = p.name.to_uppercase();
        let wire_key = p.wire_key.as_deref().unwrap_or(&name_upper);
        let key = &p.name;
        let accessor = format!("call[\"{key}\"]");
        if p.type_key == "boolean" {
            writeln!(
                out,
                "            if call.get(\"{key}\"): args.append(\"{wire_key}\")"
            )
            .unwrap();
        } else if p.type_key == "json" {
            writeln!(out, "            if \"{key}\" in call:").unwrap();
            writeln!(out, "                args.append(\"{wire_key}\")").unwrap();
            writeln!(
                out,
                "                args.append({accessor} if isinstance({accessor}, str) else json.dumps({accessor}))"
            )
            .unwrap();
        } else {
            writeln!(out, "            if \"{key}\" in call:").unwrap();
            writeln!(out, "                args.append(\"{wire_key}\")").unwrap();
            writeln!(out, "                args.append(str({accessor}))").unwrap();
        }
    }
    out.push_str("            args_list.append(args)\n");

    if cmd.response_fields.is_empty() {
        out.push_str(
            "        return await self._transport.execute_many(self._engine, args_list)\n",
        );
    } else {
        out.push_str(
            "        results = await self._transport.execute_many(self._engine, args_list)\n",
        );
        let type_name = format!(
            "_types.{}{}Response",
            engine.name.to_pascal_case(),
            cmd.name.to_pascal_case()
        );
        let field_args: Vec<String> = cmd
            .response_fields
            .iter()
            .map(|f| {
                let default = if f.optional {
                    String::new()
                } else {
                    format!(", {}", py_zero_value(&f.type_key))
                };
                format!("{}=r.get(\"{}\"{})", f.name, f.name, default)
            })
            .collect();
        writeln!(
            out,
            "        return [{type_name}({args}) for r in results]",
            args = field_args.join(", ")
        )
        .unwrap();
    }
}

fn py_zero_value(type_key: &str) -> &'static str {
    match type_key {
        "string" | "keyring" | "plaintext" | "ciphertext" | "signature" => "\"\"",
        "integer" | "key_version" => "0",
        "boolean" => "False",
        _ => "None",
    }
}
