//! Unified error hierarchy generation for Python.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use std::collections::BTreeMap;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_errors(ir)]
}

fn gen_errors(ir: &UnifiedIR) -> GeneratedFile {
    let pkg = &ir.packages.python;

    // Merge all error codes across engines, deduplicating by code name.
    let mut all_codes: BTreeMap<String, (String, u16)> = BTreeMap::new();
    for engine in &ir.engines {
        for (code, def) in &engine.error_codes {
            all_codes
                .entry(code.clone())
                .or_insert_with(|| (def.description.clone(), def.http_equiv));
        }
    }

    let mut out = String::new();
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("from __future__ import annotations\n\n\n");

    // Error class.
    out.push_str(
        r#"class ShrouDBError(Exception):
    """Base error class for all ShrouDB operations."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(f"{code} {message}")
        self.code = code
        self.message = message

    @classmethod
    def _from_server(cls, code: str, detail: str) -> ShrouDBError:
        """Create from a server error response."""
        return cls(code, detail)

    def __repr__(self) -> str:
        return f"ShrouDBError(code={self.code!r}, message={self.message!r})"


"#,
    );

    // Error code constants class.
    out.push_str("class ErrorCode:\n");
    out.push_str("    \"\"\"Known ShrouDB error codes.\"\"\"\n\n");
    for (code, (desc, _)) in &all_codes {
        writeln!(out, "    {code}: str = \"{code}\"").unwrap();
        writeln!(out, "    \"\"\"{desc}\"\"\"").unwrap();
        out.push('\n');
    }

    // If no error codes, add a pass so the class body isn't empty.
    if all_codes.is_empty() {
        out.push_str("    pass\n");
    }

    GeneratedFile {
        path: format!("{pkg}/errors.py"),
        content: out,
    }
}
