//! pyproject.toml and shroudb/__init__.py generation.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use heck::ToPascalCase;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_pyproject(ir), gen_init(ir)]
}

fn gen_pyproject(ir: &UnifiedIR) -> GeneratedFile {
    let name = &ir.packages.python;
    let version = &ir.version;

    let engine_list: Vec<_> = ir.engines.iter().map(|e| e.name.as_str()).collect();
    let desc = format!("ShrouDB unified SDK — {}", engine_list.join(", "));

    GeneratedFile {
        path: "pyproject.toml".into(),
        content: format!(
            r#"# Auto-generated by shroudb-codegen. Do not edit.

[project]
name = "{name}"
version = "{version}"
description = "{desc}"
requires-python = ">=3.10"
license = "MIT"
readme = "README.md"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
"#
        ),
    }
}

fn gen_init(ir: &UnifiedIR) -> GeneratedFile {
    let pkg = &ir.packages.python;
    let mut out = String::new();
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");

    writeln!(out, "\"\"\"{pkg} — ShrouDB unified Python SDK.\"\"\"").unwrap();
    out.push('\n');

    out.push_str("from .client import ShrouDB\n");
    out.push_str("from .errors import ShrouDBError, ErrorCode\n");

    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        writeln!(
            out,
            "from .engines.{name} import {pascal}Namespace",
            name = engine.name
        )
        .unwrap();
    }

    out.push('\n');

    // __all__
    let mut all_items = vec![
        "\"ShrouDB\"".to_string(),
        "\"ShrouDBError\"".to_string(),
        "\"ErrorCode\"".to_string(),
    ];
    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        all_items.push(format!("\"{pascal}Namespace\""));
    }
    writeln!(out, "__all__ = [\n    {},\n]", all_items.join(",\n    ")).unwrap();

    GeneratedFile {
        path: format!("{pkg}/__init__.py"),
        content: out,
    }
}
