//! Per-engine Python response type dataclass generation.

use crate::generator::GeneratedFile;
use crate::unified::ir::{EngineIR, UnifiedIR};
use heck::ToPascalCase;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    let pkg = &ir.packages.python;
    let mut files: Vec<GeneratedFile> = ir
        .engines
        .iter()
        .map(|e| gen_engine_types(pkg, e))
        .collect();
    files.push(gen_types_init(pkg, ir));
    files
}

fn gen_types_init(pkg: &str, ir: &UnifiedIR) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n");

    for engine in &ir.engines {
        let has_types = engine
            .commands
            .iter()
            .any(|c| !c.response_fields.is_empty());
        if has_types {
            writeln!(
                out,
                "from .{name} import *  # noqa: F401,F403",
                name = engine.name
            )
            .unwrap();
        }
    }

    GeneratedFile {
        path: format!("{pkg}/types/__init__.py"),
        content: out,
    }
}

fn gen_engine_types(pkg: &str, engine: &EngineIR) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from typing import Any\n\n");

    let mut has_any_types = false;

    for cmd in &engine.commands {
        if cmd.response_fields.is_empty() {
            continue;
        }

        has_any_types = true;

        let type_name = format!(
            "{}{}Response",
            engine.name.to_pascal_case(),
            cmd.name.to_pascal_case()
        );

        writeln!(out, "\n@dataclass(frozen=True)").unwrap();
        writeln!(out, "class {type_name}:").unwrap();
        writeln!(
            out,
            "    \"\"\"Response from ``{}.{}()``.\"\"\"\n",
            engine.name, cmd.name
        )
        .unwrap();

        for field in &cmd.response_fields {
            let py_type = resolve_py_type(engine, &field.type_key);
            let full_type = if field.optional {
                format!("{py_type} | None")
            } else {
                py_type
            };
            if !field.description.is_empty() {
                writeln!(out, "    # {}", field.description).unwrap();
            }
            writeln!(out, "    {}: {full_type}", field.name).unwrap();
        }
    }

    if !has_any_types {
        // No types for this engine — write an empty module.
        out.push_str("# No response types for this engine.\n");
    }

    GeneratedFile {
        path: format!("{pkg}/types/{}.py", engine.name),
        content: out,
    }
}

pub(crate) fn resolve_py_type(engine: &EngineIR, type_key: &str) -> String {
    // Check engine's defined types first.
    if let Some(t) = engine.types.get(type_key) {
        return t.python_type.clone();
    }
    // Built-in type mappings.
    match type_key {
        "string" | "keyring" | "plaintext" | "ciphertext" | "signature" => "str".into(),
        "integer" | "key_version" => "int".into(),
        "boolean" => "bool".into(),
        "json" | "map" => "dict[str, Any]".into(),
        "array" => "list[Any]".into(),
        _ => "str".into(),
    }
}
