//! ShrouDB unified client class generation for TypeScript.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use heck::ToPascalCase;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_client(ir)]
}

fn gen_client(ir: &UnifiedIR) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");

    // Imports.
    out.push_str("import type { Transport } from './transport/interface.js';\n");
    out.push_str("import { HttpTransport } from './transport/http.js';\n");
    out.push_str("import { Resp3Transport, MoatResp3Transport } from './transport/resp3.js';\n");

    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        writeln!(
            out,
            "import {{ {pascal}Namespace }} from './engines/{}.js';",
            engine.name
        )
        .unwrap();
    }

    out.push('\n');

    // Options interface.
    out.push_str("export interface ShrouDBOptions {\n");
    out.push_str("  /**\n");
    out.push_str("   * Moat gateway URL. When set, engines without a dedicated URI are\n");
    out.push_str("   * routed through this gateway.\n");
    out.push_str("   *\n");
    out.push_str("   * HTTP: `https://moat.example.com`\n");
    out.push_str("   * RESP3: `shroudb-moat://token@host:8201`\n");
    out.push_str("   */\n");
    out.push_str("  moat?: string;\n\n");

    out.push_str("  /** Bearer token for Moat HTTP authentication. */\n");
    out.push_str("  token?: string;\n\n");

    // Per-engine URI overrides.
    for engine in &ir.engines {
        writeln!(
            out,
            "  /** Direct {} URI (overrides Moat for this engine). */",
            engine.name
        )
        .unwrap();
        writeln!(out, "  {}?: string;", engine.name).unwrap();
    }

    out.push_str("}\n\n");

    // ShrouDB class.
    out.push_str("/**\n");
    out.push_str(" * ShrouDB unified client.\n");
    out.push_str(" *\n");
    out.push_str(" * Provides namespaced access to all ShrouDB engines. Each engine is\n");
    out.push_str(" * accessible as a property (e.g., `db.cipher.encrypt(...)`).\n");
    out.push_str(" *\n");
    out.push_str(" * Supply a `moat` URL to route all engines through a Moat gateway,\n");
    out.push_str(" * or individual engine URIs for direct connections.\n");
    out.push_str(" */\n");
    out.push_str("export class ShrouDB {\n");

    // Engine namespace fields.
    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        writeln!(out, "  public readonly {}: {pascal}Namespace;", engine.name).unwrap();
    }
    out.push('\n');

    out.push_str("  private transports: Transport[] = [];\n\n");

    // Constructor.
    out.push_str("  constructor(options: ShrouDBOptions) {\n");
    out.push_str("    // Resolve the default transport from the Moat URI.\n");
    out.push_str("    let defaultTransport: Transport | undefined;\n");
    out.push_str("    if (options.moat) {\n");
    out.push_str(
        "      if (options.moat.startsWith('http://') || options.moat.startsWith('https://')) {\n",
    );
    out.push_str("        const prefixes = new Map<string, string>();\n");
    for engine in &ir.engines {
        writeln!(
            out,
            "        prefixes.set(\"{}\", \"{}\");",
            engine.name, engine.http_prefix
        )
        .unwrap();
    }
    out.push_str(
        "        defaultTransport = new HttpTransport(options.moat, options.token, prefixes);\n",
    );
    out.push_str("      } else {\n");
    out.push_str("        defaultTransport = new MoatResp3Transport(options.moat);\n");
    out.push_str("      }\n");
    out.push_str("      this.transports.push(defaultTransport);\n");
    out.push_str("    }\n\n");

    // Per-engine transport resolution.
    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        writeln!(out, "    if (options.{name}) {{", name = engine.name).unwrap();
        writeln!(
            out,
            "      const t = new Resp3Transport(options.{name});",
            name = engine.name
        )
        .unwrap();
        out.push_str("      this.transports.push(t);\n");
        writeln!(
            out,
            "      this.{name} = new {pascal}Namespace(t, \"{name}\");",
            name = engine.name
        )
        .unwrap();
        writeln!(out, "    }} else if (defaultTransport) {{",).unwrap();
        writeln!(
            out,
            "      this.{name} = new {pascal}Namespace(defaultTransport, \"{name}\");",
            name = engine.name
        )
        .unwrap();
        out.push_str("    } else {\n");
        writeln!(
            out,
            "      this.{name} = new {pascal}Namespace({{ execute: () => {{ throw new Error('No transport configured for {name}. Provide a moat URL or {name} URI.'); }}, buffer: () => {{}}, flush: async () => [], close: async () => {{}} }}, \"{name}\");",
            name = engine.name
        )
        .unwrap();
        out.push_str("    }\n\n");
    }

    out.push_str("  }\n\n");

    // close()
    out.push_str("  /** Close all connections and release resources. */\n");
    out.push_str("  async close(): Promise<void> {\n");
    out.push_str("    await Promise.all(this.transports.map(t => t.close()));\n");
    out.push_str("  }\n");

    out.push_str("}\n");

    GeneratedFile {
        path: "src/client.ts".into(),
        content: out,
    }
}
