//! Per-engine namespace class generation for TypeScript.

use crate::generator::GeneratedFile;
use crate::unified::ir::{CommandIR, EngineIR, UnifiedIR};
use heck::{ToLowerCamelCase, ToPascalCase};
use std::fmt::Write;

use super::types::resolve_ts_type;

/// Escape TypeScript/JavaScript reserved words used as parameter names.
fn ts_safe_name(name: &str) -> String {
    match name {
        "new" => "newValue".into(),
        "old" => "oldValue".into(),
        "delete" => "deleteFlag".into(),
        "default" => "defaultValue".into(),
        "class" => "className".into(),
        "import" => "importData".into(),
        "export" => "exportData".into(),
        "return" => "returnValue".into(),
        "function" => "fn_".into(),
        _ => name.into(),
    }
}

pub(super) fn generate(ir: &UnifiedIR, engine: &EngineIR) -> Vec<GeneratedFile> {
    vec![gen_engine_namespace(ir, engine)]
}

fn gen_engine_namespace(_ir: &UnifiedIR, engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();

    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("import type { Transport, CommandResult } from '../transport/interface.js';\n");

    // Import response types.
    let has_types = engine
        .commands
        .iter()
        .any(|c| !c.response_fields.is_empty());
    if has_types {
        out.push_str(&format!(
            "import type * as types from '../types/{}.js';\n",
            engine.name
        ));
    }
    out.push('\n');

    writeln!(out, "/** {} — {} */", pascal, engine.description).unwrap();
    writeln!(out, "export class {pascal}Namespace {{").unwrap();
    out.push_str("  /** @internal */\n");
    out.push_str("  constructor(\n");
    out.push_str("    private readonly transport: Transport,\n");
    writeln!(
        out,
        "    private readonly engine: string = \"{}\",",
        engine.name
    )
    .unwrap();
    out.push_str("  ) {}\n");

    for cmd in &engine.commands {
        out.push('\n');
        gen_command_method(&mut out, engine, cmd);
    }

    out.push_str("}\n");

    GeneratedFile {
        path: format!("src/engines/{}.ts", engine.name),
        content: out,
    }
}

fn gen_command_method(out: &mut String, engine: &EngineIR, cmd: &CommandIR) {
    let method_name = cmd.name.to_lower_camel_case();

    // Build parameter list.
    let mut params = Vec::new();
    for p in &cmd.positional_params {
        let ts_type = resolve_ts_type(engine, &p.type_key);
        let safe_name = ts_safe_name(&p.name);
        if p.required {
            params.push(format!("{safe_name}: {ts_type}"));
        } else {
            params.push(format!("{safe_name}?: {ts_type}"));
        }
    }

    // Named params become an options object.
    if !cmd.named_params.is_empty() {
        let mut opts = Vec::new();
        for p in &cmd.named_params {
            let ts_type = resolve_ts_type(engine, &p.type_key);
            opts.push(format!("    {}?: {ts_type};", p.name));
        }
        params.push(format!("options?: {{\n{}\n  }}", opts.join("\n")));
    }

    let param_str = params.join(", ");

    // Return type.
    let return_type = if cmd.response_fields.is_empty() {
        "CommandResult".to_string()
    } else {
        format!(
            "types.{}{}Response",
            engine.name.to_pascal_case(),
            cmd.name.to_pascal_case()
        )
    };

    // JSDoc.
    let verb_display = match &cmd.subcommand {
        Some(sub) => format!("{} {}", cmd.verb, sub),
        None => cmd.verb.clone(),
    };
    writeln!(out, "  /** {verb_display} — {} */", cmd.description).unwrap();
    writeln!(
        out,
        "  async {method_name}({param_str}): Promise<{return_type}> {{"
    )
    .unwrap();

    // Build the RESP3 args array.
    out.push_str("    const args: string[] = [");
    write!(out, "\"{}\"", cmd.verb).unwrap();
    if let Some(sub) = &cmd.subcommand {
        write!(out, ", \"{sub}\"").unwrap();
    }
    out.push_str("];\n");

    // Append positional params.
    for p in &cmd.positional_params {
        let safe_name = ts_safe_name(&p.name);
        let guard = if !p.required {
            format!("    if ({safe_name} !== undefined) ")
        } else {
            "    ".to_string()
        };
        if p.type_key == "json" {
            writeln!(
                out,
                "{guard}args.push(typeof {safe_name} === 'string' ? {safe_name} : JSON.stringify({safe_name}));"
            )
            .unwrap();
        } else {
            writeln!(out, "{guard}args.push(String({safe_name}));").unwrap();
        }
    }

    // Append named (keyword) params.
    if !cmd.named_params.is_empty() {
        out.push_str("    if (options) {\n");
        for p in &cmd.named_params {
            let name_upper = p.name.to_uppercase();
            let wire_key = p.wire_key.as_deref().unwrap_or(&name_upper);
            if p.type_key == "boolean" {
                writeln!(
                    out,
                    "      if (options.{name}) args.push(\"{wire_key}\");",
                    name = p.name
                )
                .unwrap();
            } else if p.type_key == "json" {
                writeln!(
                    out,
                    "      if (options.{name} !== undefined) {{ args.push(\"{wire_key}\"); args.push(typeof options.{name} === 'string' ? options.{name} : JSON.stringify(options.{name})); }}",
                    name = p.name
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "      if (options.{name} !== undefined) {{ args.push(\"{wire_key}\"); args.push(String(options.{name})); }}",
                    name = p.name
                )
                .unwrap();
            }
        }
        out.push_str("    }\n");
    }

    // Execute and return.
    if return_type == "CommandResult" {
        out.push_str("    return this.transport.execute(this.engine, args);\n");
    } else {
        writeln!(
            out,
            "    return this.transport.execute(this.engine, args) as unknown as Promise<{return_type}>;"
        )
        .unwrap();
    }
    out.push_str("  }\n");
}
