//! Unified error hierarchy generation for TypeScript.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use std::collections::BTreeMap;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_errors(ir)]
}

fn gen_errors(ir: &UnifiedIR) -> GeneratedFile {
    // Merge all error codes across engines, deduplicating by code name.
    let mut all_codes: BTreeMap<String, (String, u16)> = BTreeMap::new();
    for engine in &ir.engines {
        for (code, def) in &engine.error_codes {
            all_codes
                .entry(code.clone())
                .or_insert_with(|| (def.description.clone(), def.http_equiv));
        }
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");

    // Error code constants.
    out.push_str("/** Known ShrouDB error codes. */\n");
    out.push_str("export const ErrorCode = {\n");
    for (code, (desc, _)) in &all_codes {
        writeln!(out, "  /** {desc} */").unwrap();
        writeln!(out, "  {code}: \"{code}\",").unwrap();
    }
    out.push_str("} as const;\n\n");
    out.push_str("export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];\n\n");

    // Error class.
    out.push_str(
        r#"/** Base error class for all ShrouDB operations. */
export class ShrouDBError extends Error {
  /** The error code from the server (e.g. "NOTFOUND", "DENIED"). */
  public readonly code: string;

  constructor(code: string, message: string) {
    super(`${code} ${message}`);
    this.name = "ShrouDBError";
    this.code = code;
  }

  /** @internal Create from a server error response. */
  static _fromServer(code: string, detail: string): ShrouDBError {
    return new ShrouDBError(code, detail);
  }
}
"#,
    );

    GeneratedFile {
        path: "src/errors.ts".into(),
        content: out,
    }
}
