//! package.json, tsconfig.json, postinstall.js, and src/index.ts generation.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use heck::ToPascalCase;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![
        gen_package_json(ir),
        gen_tsconfig(),
        gen_postinstall(ir),
        gen_index(ir),
    ]
}

fn gen_package_json(ir: &UnifiedIR) -> GeneratedFile {
    let name = &ir.packages.typescript;
    let version = &ir.version;

    let engine_list: Vec<_> = ir.engines.iter().map(|e| e.name.as_str()).collect();
    let desc = format!("ShrouDB unified SDK — {}", engine_list.join(", "));

    GeneratedFile {
        path: "package.json".into(),
        content: format!(
            r#"{{
  "name": "{name}",
  "version": "{version}",
  "description": "{desc}",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "exports": {{
    ".": {{
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js"
    }}
  }},
  "scripts": {{
    "build": "tsc",
    "prepublishOnly": "npm run build",
    "postinstall": "node postinstall.js"
  }},
  "repository": {{
    "type": "git",
    "url": "https://github.com/shroudb/shroudb-sdk-typescript.git"
  }},
  "publishConfig": {{
    "registry": "https://npm.pkg.github.com"
  }},
  "license": "MIT",
  "engines": {{
    "node": ">=18"
  }},
  "devDependencies": {{
    "@types/node": "^22",
    "typescript": "^5"
  }}
}}
"#
        ),
    }
}

fn gen_tsconfig() -> GeneratedFile {
    GeneratedFile {
        path: "tsconfig.json".into(),
        content: r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "Node16",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "moduleResolution": "Node16",
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src"]
}
"#
        .into(),
    }
}

fn gen_postinstall(ir: &UnifiedIR) -> GeneratedFile {
    let pkg = &ir.packages.typescript;
    GeneratedFile {
        path: "postinstall.js".into(),
        content: format!(
            r#"#!/usr/bin/env node
"use strict";

// Inject a pointer into the project's root AGENTS.md so AI coding assistants
// can discover the ShrouDB SDK documentation automatically.

const fs = require("fs");
const path = require("path");

const MARKER = "{pkg}/AGENTS.md";
const SECTION = `

## ShrouDB SDK

See [node_modules/{pkg}/AGENTS.md](node_modules/{pkg}/AGENTS.md) for ShrouDB SDK commands, types, and usage examples.
`;

// Walk up from node_modules/{pkg}/ to find the project root.
let dir = path.resolve(__dirname, "..", "..");
const root = path.parse(dir).root;

while (dir !== root) {{
  const pkg = path.join(dir, "package.json");
  if (fs.existsSync(pkg)) {{
    const agents = path.join(dir, "AGENTS.md");
    if (fs.existsSync(agents)) {{
      const content = fs.readFileSync(agents, "utf-8");
      if (!content.includes(MARKER)) {{
        fs.appendFileSync(agents, SECTION);
      }}
    }} else {{
      fs.writeFileSync(agents, SECTION.trimStart());
    }}
    break;
  }}
  dir = path.dirname(dir);
}}
"#
        ),
    }
}

fn gen_index(ir: &UnifiedIR) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("export { ShrouDB, type ShrouDBOptions } from './client.js';\n");
    out.push_str("export { ShrouDBError } from './errors.js';\n");

    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        writeln!(
            out,
            "export {{ {pascal}Namespace }} from './engines/{name}.js';",
            name = engine.name
        )
        .unwrap();
    }

    out.push('\n');
    for engine in &ir.engines {
        writeln!(out, "export type * from './types/{}.js';", engine.name).unwrap();
    }

    GeneratedFile {
        path: "src/index.ts".into(),
        content: out,
    }
}
