//! Per-engine TypeScript response type interface generation.

use crate::generator::GeneratedFile;
use crate::unified::ir::{EngineIR, UnifiedIR};
use heck::ToPascalCase;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    ir.engines.iter().map(|e| gen_engine_types(ir, e)).collect()
}

fn gen_engine_types(_ir: &UnifiedIR, engine: &EngineIR) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");

    for cmd in &engine.commands {
        if cmd.response_fields.is_empty() {
            continue;
        }

        let type_name = format!(
            "{}{}Response",
            engine.name.to_pascal_case(),
            cmd.name.to_pascal_case()
        );

        writeln!(
            out,
            "/** Response from `{}.{}()`. */",
            engine.name, cmd.name
        )
        .unwrap();
        writeln!(out, "export interface {type_name} {{").unwrap();

        for field in &cmd.response_fields {
            let ts_type = resolve_ts_type(engine, &field.type_key);
            let opt = if field.optional { "?" } else { "" };
            if !field.description.is_empty() {
                writeln!(out, "  /** {} */", field.description).unwrap();
            }
            writeln!(out, "  {}{opt}: {ts_type};", field.name).unwrap();
        }

        out.push_str("}\n\n");
    }

    GeneratedFile {
        path: format!("src/types/{}.ts", engine.name),
        content: out,
    }
}

pub(crate) fn resolve_ts_type(engine: &EngineIR, type_key: &str) -> String {
    // Check engine's defined types first.
    if let Some(t) = engine.types.get(type_key) {
        return t.typescript_type.clone();
    }
    // Built-in type mappings.
    match type_key {
        "string" => "string".into(),
        "integer" => "number".into(),
        "boolean" => "boolean".into(),
        "json" => "Record<string, unknown>".into(),
        "array" => "unknown[]".into(),
        _ => "unknown".into(),
    }
}
