//! ShrouDB unified client struct generation for Go.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use heck::ToPascalCase;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_client(ir)]
}

fn gen_client(ir: &UnifiedIR) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("package shroudb\n\n");
    out.push_str("import (\n");
    out.push_str("\t\"fmt\"\n");
    out.push_str("\t\"strings\"\n");
    out.push_str(")\n\n");

    // Options struct.
    out.push_str("// Options configures the ShrouDB client.\n");
    out.push_str("type Options struct {\n");
    out.push_str("\t// Moat is the Moat gateway URL. When set, engines without a dedicated\n");
    out.push_str("\t// URI are routed through this gateway.\n");
    out.push_str("\t//\n");
    out.push_str("\t// HTTP:  https://moat.example.com\n");
    out.push_str("\t// RESP3: shroudb-moat://token@host:8201\n");
    out.push_str("\tMoat string\n\n");
    out.push_str("\t// Token is the bearer token for Moat HTTP authentication.\n");
    out.push_str("\tToken string\n\n");

    // Per-engine URI overrides.
    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        writeln!(
            out,
            "\t// {pascal} is the direct {} URI (overrides Moat for this engine).",
            engine.name
        )
        .unwrap();
        writeln!(out, "\t{pascal} string").unwrap();
    }
    out.push_str("}\n\n");

    // ShrouDB struct.
    out.push_str("// ShrouDB is the unified client for all ShrouDB engines.\n");
    out.push_str("//\n");
    out.push_str("// Provides namespaced access to all engines. Each engine is accessible\n");
    out.push_str("// as a field (e.g., db.Cipher.Encrypt(ctx, ...)).\n");
    out.push_str("//\n");
    out.push_str("// Supply a Moat URL to route all engines through a Moat gateway,\n");
    out.push_str("// or individual engine URIs for direct connections.\n");
    out.push_str("type ShrouDB struct {\n");

    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        writeln!(out, "\t{pascal} *{pascal}Namespace").unwrap();
    }
    out.push_str("\n\ttransports []Transport\n");
    out.push_str("}\n\n");

    // Constructor.
    out.push_str("// New creates a new ShrouDB client with the given options.\n");
    out.push_str("func New(opts Options) (*ShrouDB, error) {\n");
    out.push_str("\tdb := &ShrouDB{}\n\n");

    // Default transport from Moat URI.
    out.push_str("\tvar defaultTransport Transport\n");
    out.push_str("\tif opts.Moat != \"\" {\n");
    out.push_str("\t\tif strings.HasPrefix(opts.Moat, \"http://\") || strings.HasPrefix(opts.Moat, \"https://\") {\n");
    out.push_str("\t\t\tprefixes := map[string]string{\n");
    for engine in &ir.engines {
        writeln!(
            out,
            "\t\t\t\t\"{}\": \"{}\",",
            engine.name, engine.http_prefix
        )
        .unwrap();
    }
    out.push_str("\t\t\t}\n");
    out.push_str("\t\t\tdefaultTransport = NewHttpTransport(opts.Moat, opts.Token, prefixes)\n");
    out.push_str("\t\t} else {\n");
    out.push_str("\t\t\tt, err := NewMoatResp3Transport(opts.Moat)\n");
    out.push_str("\t\t\tif err != nil {\n");
    out.push_str("\t\t\t\treturn nil, fmt.Errorf(\"moat transport: %w\", err)\n");
    out.push_str("\t\t\t}\n");
    out.push_str("\t\t\tdefaultTransport = t\n");
    out.push_str("\t\t}\n");
    out.push_str("\t\tdb.transports = append(db.transports, defaultTransport)\n");
    out.push_str("\t}\n\n");

    // Per-engine transport resolution.
    for engine in &ir.engines {
        let pascal = engine.name.to_pascal_case();
        writeln!(out, "\tif opts.{pascal} != \"\" {{").unwrap();
        writeln!(out, "\t\tt, err := NewResp3Transport(opts.{pascal})").unwrap();
        out.push_str("\t\tif err != nil {\n");
        writeln!(
            out,
            "\t\t\treturn nil, fmt.Errorf(\"{} transport: %w\", err)",
            engine.name
        )
        .unwrap();
        out.push_str("\t\t}\n");
        out.push_str("\t\tdb.transports = append(db.transports, t)\n");
        writeln!(
            out,
            "\t\tdb.{pascal} = new{pascal}Namespace(t, \"{}\")",
            engine.name
        )
        .unwrap();
        out.push_str("\t} else if defaultTransport != nil {\n");
        writeln!(
            out,
            "\t\tdb.{pascal} = new{pascal}Namespace(defaultTransport, \"{}\")",
            engine.name
        )
        .unwrap();
        out.push_str("\t}\n\n");
    }

    out.push_str("\treturn db, nil\n");
    out.push_str("}\n\n");

    // Close method.
    out.push_str("// Close releases all connections held by the client.\n");
    out.push_str("func (db *ShrouDB) Close() error {\n");
    out.push_str("\tvar firstErr error\n");
    out.push_str("\tfor _, t := range db.transports {\n");
    out.push_str("\t\tif err := t.Close(); err != nil && firstErr == nil {\n");
    out.push_str("\t\t\tfirstErr = err\n");
    out.push_str("\t\t}\n");
    out.push_str("\t}\n");
    out.push_str("\treturn firstErr\n");
    out.push_str("}\n");

    GeneratedFile {
        path: "client.go".into(),
        content: out,
    }
}
