//! Per-engine namespace struct and method generation for Go.

use crate::generator::GeneratedFile;
use crate::unified::ir::{CommandIR, EngineIR, UnifiedIR};
use heck::ToPascalCase;
use std::fmt::Write;

use super::types::resolve_go_type;

pub(super) fn generate(_ir: &UnifiedIR, engine: &EngineIR) -> Vec<GeneratedFile> {
    vec![gen_engine_file(engine)]
}

fn gen_engine_file(engine: &EngineIR) -> GeneratedFile {
    let pascal = engine.name.to_pascal_case();
    let mut out = String::new();

    let needs_base64 = engine.commands.iter().any(|c| {
        c.positional_params
            .iter()
            .any(|p| engine.is_base64_type(&p.type_key))
    });

    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("package shroudb\n\n");
    out.push_str("import (\n");
    out.push_str("\t\"context\"\n");
    if needs_base64 {
        out.push_str("\t\"encoding/base64\"\n");
    }
    out.push_str("\t\"encoding/json\"\n");
    out.push_str("\t\"fmt\"\n");
    out.push_str(")\n\n");

    // Namespace struct.
    writeln!(
        out,
        "// {pascal}Namespace provides methods for the {} engine.",
        engine.name
    )
    .unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// {}", engine.description).unwrap();
    writeln!(out, "type {pascal}Namespace struct {{").unwrap();
    out.push_str("\ttransport Transport\n");
    out.push_str("\tengine    string\n");
    out.push_str("}\n\n");

    // Constructor (internal).
    writeln!(
        out,
        "func new{pascal}Namespace(transport Transport, engine string) *{pascal}Namespace {{"
    )
    .unwrap();
    writeln!(
        out,
        "\treturn &{pascal}Namespace{{transport: transport, engine: engine}}"
    )
    .unwrap();
    out.push_str("}\n");

    for cmd in &engine.commands {
        out.push('\n');
        gen_command_method(&mut out, engine, cmd);
    }

    GeneratedFile {
        path: format!("{}.go", engine.name),
        content: out,
    }
}

fn gen_command_method(out: &mut String, engine: &EngineIR, cmd: &CommandIR) {
    let pascal = engine.name.to_pascal_case();
    let method_name = cmd.name.to_pascal_case();

    // Build parameter list.
    let mut params = vec!["ctx context.Context".to_string()];
    for p in &cmd.positional_params {
        let go_type = if engine.is_base64_type(&p.type_key) {
            "[]byte".to_string()
        } else {
            resolve_go_type(engine, &p.type_key)
        };
        params.push(format!("{} {go_type}", safe_go_param(&p.name)));
    }
    if !cmd.named_params.is_empty() {
        let opts_type = format!("{pascal}{method_name}Options");
        params.push(format!("opts *{opts_type}"));
    }
    let param_str = params.join(", ");

    // Return type.
    let has_response = !cmd.response_fields.is_empty();
    let response_type = format!("{pascal}{method_name}Response");
    let return_type = if has_response {
        format!("(*{response_type}, error)")
    } else {
        "error".to_string()
    };

    // Doc comment.
    let verb_display = match &cmd.subcommand {
        Some(sub) => format!("{} {}", cmd.verb, sub),
        None => cmd.verb.clone(),
    };
    writeln!(
        out,
        "// {method_name} executes {verb_display} — {}",
        cmd.description
    )
    .unwrap();
    writeln!(
        out,
        "func (ns *{pascal}Namespace) {method_name}({param_str}) {return_type} {{"
    )
    .unwrap();

    // Build args slice.
    let mut initial_args = vec![format!("\"{}\"", cmd.verb)];
    if let Some(sub) = &cmd.subcommand {
        initial_args.push(format!("\"{sub}\""));
    }
    writeln!(out, "\targs := []string{{{}}}", initial_args.join(", ")).unwrap();

    // Append positional params.
    for p in &cmd.positional_params {
        let name = safe_go_param(&p.name);
        // Guard optional positional params.
        if !p.required {
            let go_type = if engine.is_base64_type(&p.type_key) {
                "[]byte".to_string()
            } else {
                resolve_go_type(engine, &p.type_key)
            };
            let zero_check = match go_type.as_str() {
                "string" => format!("{name} != \"\""),
                "int" => format!("{name} != 0"),
                "bool" => name.to_string(),
                "[]byte" => format!("len({name}) > 0"),
                _ => format!("{name} != nil"),
            };
            writeln!(out, "\tif {zero_check} {{").unwrap();
            if engine.is_base64_type(&p.type_key) {
                writeln!(
                    out,
                    "\t\targs = append(args, base64.StdEncoding.EncodeToString({name}))"
                )
                .unwrap();
            } else if is_string_like(&p.type_key) {
                writeln!(out, "\t\targs = append(args, {name})").unwrap();
            } else if p.type_key == "json" || p.type_key == "map" {
                writeln!(out, "\t\tjsonBytes, _ := json.Marshal({name})").unwrap();
                writeln!(out, "\t\targs = append(args, string(jsonBytes))").unwrap();
            } else {
                writeln!(out, "\t\targs = append(args, fmt.Sprint({name}))").unwrap();
            }
            out.push_str("\t}\n");
            continue;
        }
        if p.variadic {
            if is_string_like(&p.type_key) {
                writeln!(out, "\targs = append(args, {name}...)").unwrap();
            } else {
                writeln!(out, "\tfor _, v := range {name} {{").unwrap();
                writeln!(out, "\t\targs = append(args, fmt.Sprint(v))").unwrap();
                out.push_str("\t}\n");
            }
        } else if p.type_key == "json" || p.type_key == "map" {
            writeln!(out, "\t{name}JSON, err := json.Marshal({name})").unwrap();
            writeln!(out, "\tif err != nil {{").unwrap();
            if has_response {
                writeln!(
                    out,
                    "\t\treturn nil, fmt.Errorf(\"marshal {}: %w\", err)",
                    p.name
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "\t\treturn fmt.Errorf(\"marshal {}: %w\", err)",
                    p.name
                )
                .unwrap();
            }
            out.push_str("\t}\n");
            writeln!(out, "\targs = append(args, string({name}JSON))").unwrap();
        } else if engine.is_base64_type(&p.type_key) {
            // Auto-encode []byte to base64 for the wire protocol.
            writeln!(
                out,
                "\targs = append(args, base64.StdEncoding.EncodeToString({name}))"
            )
            .unwrap();
        } else if is_string_like(&p.type_key) {
            writeln!(out, "\targs = append(args, {name})").unwrap();
        } else {
            writeln!(out, "\targs = append(args, fmt.Sprint({name}))").unwrap();
        }
    }

    // Append named (keyword) params.
    if !cmd.named_params.is_empty() {
        out.push_str("\tif opts != nil {\n");
        for p in &cmd.named_params {
            let default_key = p.name.to_uppercase();
            let wire_key = p.wire_key.as_deref().unwrap_or(&default_key);
            let field_name = p.name.to_pascal_case();
            if p.type_key == "boolean" {
                writeln!(out, "\t\tif opts.{field_name} {{").unwrap();
                writeln!(out, "\t\t\targs = append(args, \"{wire_key}\")").unwrap();
                out.push_str("\t\t}\n");
            } else if p.type_key == "json" || p.type_key == "map" {
                writeln!(out, "\t\tif opts.{field_name} != nil {{").unwrap();
                writeln!(
                    out,
                    "\t\t\tjsonBytes, err := json.Marshal(opts.{field_name})"
                )
                .unwrap();
                writeln!(out, "\t\t\tif err == nil {{").unwrap();
                writeln!(
                    out,
                    "\t\t\t\targs = append(args, \"{wire_key}\", string(jsonBytes))"
                )
                .unwrap();
                out.push_str("\t\t\t}\n");
                out.push_str("\t\t}\n");
            } else {
                writeln!(out, "\t\tif opts.{field_name} != nil {{").unwrap();
                writeln!(
                    out,
                    "\t\t\targs = append(args, \"{wire_key}\", fmt.Sprint(*opts.{field_name}))"
                )
                .unwrap();
                out.push_str("\t\t}\n");
            }
        }
        out.push_str("\t}\n");
    }

    // Execute and return.
    if has_response {
        out.push_str("\traw, err := ns.transport.Execute(ctx, ns.engine, args)\n");
        out.push_str("\tif err != nil {\n");
        out.push_str("\t\treturn nil, err\n");
        out.push_str("\t}\n");

        // Marshal the raw map back to JSON and unmarshal into the typed struct.
        writeln!(out, "\tvar resp {response_type}").unwrap();
        out.push_str("\tjsonBytes, err := json.Marshal(raw)\n");
        out.push_str("\tif err != nil {\n");
        out.push_str("\t\treturn nil, fmt.Errorf(\"marshal response: %w\", err)\n");
        out.push_str("\t}\n");
        out.push_str("\tif err := json.Unmarshal(jsonBytes, &resp); err != nil {\n");
        out.push_str("\t\treturn nil, fmt.Errorf(\"unmarshal response: %w\", err)\n");
        out.push_str("\t}\n");
        out.push_str("\treturn &resp, nil\n");
    } else {
        out.push_str("\t_, err := ns.transport.Execute(ctx, ns.engine, args)\n");
        out.push_str("\treturn err\n");
    }

    out.push_str("}\n");
}

/// Ensure Go parameter names don't conflict with reserved words.
fn safe_go_param(name: &str) -> String {
    match name {
        "type" => "typ".into(),
        "range" => "rng".into(),
        "map" => "m".into(),
        "func" => "fn_".into(),
        "var" => "v".into(),
        "interface" => "iface".into(),
        "package" => "pkg".into(),
        "default" => "def".into(),
        "select" => "sel".into(),
        "chan" => "ch".into(),
        "go" => "goVal".into(),
        "new" => "newValue".into(),
        "old" => "oldValue".into(),
        "delete" => "del".into(),
        "import" => "imp".into(),
        "return" => "ret".into(),
        "json" => "jsonData".into(),
        "error" => "errVal".into(),
        "string" => "str".into(),
        "int" => "n".into(),
        "from" => "fromVal".into(),
        other => other.into(),
    }
}

fn is_string_like(type_key: &str) -> bool {
    matches!(
        type_key,
        "string" | "keyring" | "plaintext" | "ciphertext" | "signature"
    )
}
