//! Unified error type and error code constants for Go.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use std::collections::BTreeMap;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_errors(ir)]
}

fn gen_errors(ir: &UnifiedIR) -> GeneratedFile {
    // Merge all error codes across engines, deduplicating by code name.
    let mut all_codes: BTreeMap<String, (String, u16)> = BTreeMap::new();
    for engine in &ir.engines {
        for (code, def) in &engine.error_codes {
            all_codes
                .entry(code.clone())
                .or_insert_with(|| (def.description.clone(), def.http_equiv));
        }
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("package shroudb\n\n");
    out.push_str("import \"fmt\"\n\n");

    // ShrouDBError type.
    out.push_str("// ShrouDBError represents an error returned by a ShrouDB engine.\n");
    out.push_str("type ShrouDBError struct {\n");
    out.push_str("\t// Code is the error code from the server (e.g. \"NOTFOUND\", \"DENIED\").\n");
    out.push_str("\tCode    string\n");
    out.push_str("\t// Message is the human-readable error detail.\n");
    out.push_str("\tMessage string\n");
    out.push_str("}\n\n");

    // Error() method.
    out.push_str("// Error implements the error interface.\n");
    out.push_str("func (e *ShrouDBError) Error() string {\n");
    out.push_str("\treturn fmt.Sprintf(\"%s %s\", e.Code, e.Message)\n");
    out.push_str("}\n\n");

    // IsCode helper.
    out.push_str("// IsCode returns true if err is a ShrouDBError with the given code.\n");
    out.push_str("func IsCode(err error, code string) bool {\n");
    out.push_str("\tif e, ok := err.(*ShrouDBError); ok {\n");
    out.push_str("\t\treturn e.Code == code\n");
    out.push_str("\t}\n");
    out.push_str("\treturn false\n");
    out.push_str("}\n");

    // Error code constants.
    if !all_codes.is_empty() {
        out.push_str("\n// Known ShrouDB error codes.\n");
        out.push_str("const (\n");
        for (code, (desc, _)) in &all_codes {
            writeln!(out, "\t// Err{code} — {desc}").unwrap();
            writeln!(out, "\tErr{code} = \"{code}\"").unwrap();
        }
        out.push_str(")\n");
    }

    GeneratedFile {
        path: "errors.go".into(),
        content: out,
    }
}
