//! Transport interface, RESP3 codec, and HTTP transport generation for Go.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;

pub(super) fn generate(_ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_transport(), gen_resp3(), gen_http()]
}

fn gen_transport() -> GeneratedFile {
    GeneratedFile {
        path: "transport.go".into(),
        content: r#"// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import "context"

// Transport abstracts the wire protocol used to communicate with ShrouDB
// engines. Implementations handle connection lifecycle and serialization.
type Transport interface {
	// Execute sends a command and returns the parsed response.
	Execute(ctx context.Context, engine string, args []string) (map[string]any, error)

	// ExecutePipeline sends a server-side atomic PIPELINE with N nested
	// sub-command arrays in a single RESP3 frame and returns one result per
	// sub-command, in order. Pass a non-empty requestID for idempotent retry —
	// repeated calls with the same ID return the cached result without
	// re-executing.
	//
	// Only supported over RESP3; HTTP transports return ErrPipelineNotSupported.
	ExecutePipeline(ctx context.Context, engine string, commands [][]string, requestID string) ([]map[string]any, error)

	// Close releases all connections held by this transport.
	Close() error
}
"#
        .into(),
    }
}

fn gen_resp3() -> GeneratedFile {
    GeneratedFile {
        path: "resp3.go".into(),
        content: r#"// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"bufio"
	"context"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"net"
	"net/url"
	"strconv"
	"strings"
	"sync"
)

// resp3Conn wraps a raw TCP/TLS connection with a buffered reader for RESP3 parsing.
type resp3Conn struct {
	conn   net.Conn
	reader *bufio.Reader
}

func newResp3Conn(conn net.Conn) *resp3Conn {
	return &resp3Conn{
		conn:   conn,
		reader: bufio.NewReader(conn),
	}
}

func (c *resp3Conn) send(args []string) error {
	var b strings.Builder
	fmt.Fprintf(&b, "*%d\r\n", len(args))
	for _, arg := range args {
		fmt.Fprintf(&b, "$%d\r\n%s\r\n", len(arg), arg)
	}
	_, err := c.conn.Write([]byte(b.String()))
	return err
}

// sendPipeline writes a PIPELINE frame: outer array of
// [prefix..., REQUEST_ID?, ...nested sub-command arrays].
func (c *resp3Conn) sendPipeline(prefix []string, commands [][]string, requestID string) error {
	var b strings.Builder
	keywordCount := 0
	if requestID != "" {
		keywordCount = 2
	}
	outerLen := len(prefix) + keywordCount + len(commands)
	fmt.Fprintf(&b, "*%d\r\n", outerLen)
	for _, p := range prefix {
		fmt.Fprintf(&b, "$%d\r\n%s\r\n", len(p), p)
	}
	if requestID != "" {
		b.WriteString("$10\r\nREQUEST_ID\r\n")
		fmt.Fprintf(&b, "$%d\r\n%s\r\n", len(requestID), requestID)
	}
	for _, sub := range commands {
		fmt.Fprintf(&b, "*%d\r\n", len(sub))
		for _, arg := range sub {
			fmt.Fprintf(&b, "$%d\r\n%s\r\n", len(arg), arg)
		}
	}
	_, err := c.conn.Write([]byte(b.String()))
	return err
}

func (c *resp3Conn) readReply() (any, error) {
	line, err := c.reader.ReadString('\n')
	if err != nil {
		return nil, err
	}
	if len(line) < 3 || line[len(line)-2] != '\r' {
		return nil, fmt.Errorf("resp3: malformed line: %q", line)
	}
	tag := line[0]
	payload := line[1 : len(line)-2]

	switch tag {
	case '+':
		return payload, nil
	case '-':
		idx := strings.Index(payload, " ")
		code := payload
		detail := ""
		if idx >= 0 {
			code = payload[:idx]
			detail = payload[idx+1:]
		}
		// Engines send "ERR {msg}" — infer structured code from message.
		if code == "ERR" {
			code = inferErrorCode(detail)
		}
		return nil, &ShrouDBError{Code: code, Message: detail}
	case ':':
		n, err := strconv.Atoi(payload)
		if err != nil {
			return nil, fmt.Errorf("resp3: invalid integer: %q", payload)
		}
		return n, nil
	case '$':
		length, err := strconv.Atoi(payload)
		if err != nil {
			return nil, fmt.Errorf("resp3: invalid bulk length: %q", payload)
		}
		if length < 0 {
			return nil, nil
		}
		buf := make([]byte, length+2) // +2 for \r\n
		if _, err := c.reader.Read(buf); err != nil {
			return nil, err
		}
		return string(buf[:length]), nil
	case '*':
		count, err := strconv.Atoi(payload)
		if err != nil {
			return nil, fmt.Errorf("resp3: invalid array count: %q", payload)
		}
		if count < 0 {
			return nil, nil
		}
		items := make([]any, count)
		for i := 0; i < count; i++ {
			items[i], err = c.readReply()
			if err != nil {
				return nil, err
			}
		}
		return items, nil
	case '%':
		count, err := strconv.Atoi(payload)
		if err != nil {
			return nil, fmt.Errorf("resp3: invalid map count: %q", payload)
		}
		m := make(map[string]any, count)
		for i := 0; i < count; i++ {
			key, err := c.readReply()
			if err != nil {
				return nil, err
			}
			val, err := c.readReply()
			if err != nil {
				return nil, err
			}
			m[fmt.Sprint(key)] = val
		}
		return m, nil
	default:
		return payload, nil
	}
}

func (c *resp3Conn) close() error {
	return c.conn.Close()
}

// resp3ConnParams holds parsed RESP3 URI components.
type resp3ConnParams struct {
	Host  string
	Port  int
	TLS   bool
	Token string
}

// parseResp3URI parses a ShrouDB RESP3 URI into connection parameters.
//
// Format: scheme[+tls]://[token@]host[:port]
func parseResp3URI(uri string) (resp3ConnParams, error) {
	p := resp3ConnParams{Port: 6399}

	u, err := url.Parse(uri)
	if err != nil {
		return p, fmt.Errorf("invalid ShrouDB URI: %s: %w", uri, err)
	}

	p.TLS = strings.HasSuffix(u.Scheme, "+tls")
	p.Host = u.Hostname()
	if portStr := u.Port(); portStr != "" {
		port, err := strconv.Atoi(portStr)
		if err != nil {
			return p, fmt.Errorf("invalid port in URI: %s", uri)
		}
		p.Port = port
	}
	if u.User != nil {
		p.Token = u.User.Username()
	}

	return p, nil
}

// resp3Pool is a simple connection pool for RESP3 connections.
type resp3Pool struct {
	params resp3ConnParams
	mu     sync.Mutex
	idle   []*resp3Conn
}

func newResp3Pool(params resp3ConnParams) *resp3Pool {
	return &resp3Pool{params: params}
}

func (p *resp3Pool) acquire() (*resp3Conn, error) {
	p.mu.Lock()
	if len(p.idle) > 0 {
		c := p.idle[len(p.idle)-1]
		p.idle = p.idle[:len(p.idle)-1]
		p.mu.Unlock()
		return c, nil
	}
	p.mu.Unlock()

	addr := net.JoinHostPort(p.params.Host, strconv.Itoa(p.params.Port))
	var rawConn net.Conn
	var err error
	if p.params.TLS {
		rawConn, err = tls.Dial("tcp", addr, &tls.Config{ServerName: p.params.Host})
	} else {
		rawConn, err = net.Dial("tcp", addr)
	}
	if err != nil {
		return nil, fmt.Errorf("resp3: dial %s: %w", addr, err)
	}

	c := newResp3Conn(rawConn)

	if p.params.Token != "" {
		if err := c.send([]string{"AUTH", p.params.Token}); err != nil {
			c.close()
			return nil, fmt.Errorf("resp3: auth send: %w", err)
		}
		if _, err := c.readReply(); err != nil {
			c.close()
			return nil, fmt.Errorf("resp3: auth: %w", err)
		}
	}

	return c, nil
}

func (p *resp3Pool) release(c *resp3Conn) {
	p.mu.Lock()
	p.idle = append(p.idle, c)
	p.mu.Unlock()
}

func (p *resp3Pool) close() error {
	p.mu.Lock()
	defer p.mu.Unlock()
	var firstErr error
	for _, c := range p.idle {
		if err := c.close(); err != nil && firstErr == nil {
			firstErr = err
		}
	}
	p.idle = nil
	return firstErr
}

// Resp3Transport implements Transport for direct engine RESP3 connections.
type Resp3Transport struct {
	pool *resp3Pool
}

// NewResp3Transport creates a RESP3 transport from a ShrouDB URI.
func NewResp3Transport(uri string) (*Resp3Transport, error) {
	params, err := parseResp3URI(uri)
	if err != nil {
		return nil, err
	}
	return &Resp3Transport{pool: newResp3Pool(params)}, nil
}

// Execute sends a command over RESP3 and returns the parsed response map.
func (t *Resp3Transport) Execute(ctx context.Context, engine string, args []string) (map[string]any, error) {
	conn, err := t.pool.acquire()
	if err != nil {
		return nil, err
	}
	defer t.pool.release(conn)

	if err := conn.send(args); err != nil {
		return nil, err
	}
	raw, err := conn.readReply()
	if err != nil {
		return nil, err
	}
	return parseResp3Response(raw), nil
}

// ExecutePipeline sends a server-side atomic PIPELINE over RESP3.
func (t *Resp3Transport) ExecutePipeline(ctx context.Context, engine string, commands [][]string, requestID string) ([]map[string]any, error) {
	conn, err := t.pool.acquire()
	if err != nil {
		return nil, err
	}
	defer t.pool.release(conn)

	if err := conn.sendPipeline([]string{"PIPELINE"}, commands, requestID); err != nil {
		return nil, err
	}
	raw, err := conn.readReply()
	if err != nil {
		return nil, err
	}
	items, ok := raw.([]any)
	if !ok {
		return nil, &ShrouDBError{Code: "ERR", Message: "PIPELINE response was not an array"}
	}
	out := make([]map[string]any, len(items))
	for i, item := range items {
		out[i] = parseResp3Response(item)
	}
	return out, nil
}

// Close releases all pooled connections.
func (t *Resp3Transport) Close() error {
	return t.pool.close()
}

// MoatResp3Transport implements Transport for Moat gateway RESP3 connections.
// Commands are prefixed with the uppercase engine name.
type MoatResp3Transport struct {
	pool *resp3Pool
}

// NewMoatResp3Transport creates a Moat RESP3 transport from a ShrouDB URI.
func NewMoatResp3Transport(uri string) (*MoatResp3Transport, error) {
	params, err := parseResp3URI(uri)
	if err != nil {
		return nil, err
	}
	return &MoatResp3Transport{pool: newResp3Pool(params)}, nil
}

// Execute sends an engine-prefixed command over RESP3.
func (t *MoatResp3Transport) Execute(ctx context.Context, engine string, args []string) (map[string]any, error) {
	prefixed := make([]string, 0, len(args)+1)
	prefixed = append(prefixed, strings.ToUpper(engine))
	prefixed = append(prefixed, args...)

	conn, err := t.pool.acquire()
	if err != nil {
		return nil, err
	}
	defer t.pool.release(conn)

	if err := conn.send(prefixed); err != nil {
		return nil, err
	}
	raw, err := conn.readReply()
	if err != nil {
		return nil, err
	}
	return parseResp3Response(raw), nil
}

// ExecutePipeline sends a server-side atomic PIPELINE through a Moat gateway,
// prefixing the frame with the uppercase engine name.
func (t *MoatResp3Transport) ExecutePipeline(ctx context.Context, engine string, commands [][]string, requestID string) ([]map[string]any, error) {
	conn, err := t.pool.acquire()
	if err != nil {
		return nil, err
	}
	defer t.pool.release(conn)

	prefix := []string{strings.ToUpper(engine), "PIPELINE"}
	if err := conn.sendPipeline(prefix, commands, requestID); err != nil {
		return nil, err
	}
	raw, err := conn.readReply()
	if err != nil {
		return nil, err
	}
	items, ok := raw.([]any)
	if !ok {
		return nil, &ShrouDBError{Code: "ERR", Message: "PIPELINE response was not an array"}
	}
	out := make([]map[string]any, len(items))
	for i, item := range items {
		out[i] = parseResp3Response(item)
	}
	return out, nil
}

// Close releases all pooled connections.
func (t *MoatResp3Transport) Close() error {
	return t.pool.close()
}

// parseResp3Response converts a raw RESP3 value into a response map.
// Bulk strings containing JSON are parsed into maps automatically.
// inferErrorCode maps generic "ERR {message}" to structured error codes.
func inferErrorCode(message string) string {
	m := strings.ToLower(message)
	switch {
	case strings.Contains(m, "not found"):
		return "NOTFOUND"
	case strings.Contains(m, "already exists"):
		return "EXISTS"
	case strings.Contains(m, "is deleted"), strings.Contains(m, "soft-revoked"):
		return "DELETED"
	case strings.Contains(m, "access denied"), strings.Contains(m, "policy denied"):
		return "DENIED"
	case strings.Contains(m, "not authenticated"):
		return "NOT_AUTHENTICATED"
	case strings.Contains(m, "verification failed"):
		return "VERIFICATION_FAILED"
	case strings.Contains(m, "account locked"):
		return "ACCOUNT_LOCKED"
	case strings.Contains(m, "invalid token"), strings.Contains(m, "token reuse"):
		return "INVALID_TOKEN"
	case strings.Contains(m, "invalid argument"), strings.Contains(m, "invalid path"), strings.Contains(m, "bad argument"), strings.Contains(m, "unknown command"):
		return "BADARG"
	case strings.Contains(m, "schema validation"):
		return "SCHEMA_VALIDATION"
	case strings.Contains(m, "capability"), strings.Contains(m, "unavailable"):
		return "CAPABILITY_MISSING"
	case strings.Contains(m, "retired"):
		return "RETIRED"
	case strings.Contains(m, "disabled"):
		return "DISABLED"
	case strings.Contains(m, "shredded"), strings.Contains(m, "crypto-shred"):
		return "SHREDDED"
	case strings.Contains(m, "revoked"):
		return "REVOKED"
	case strings.Contains(m, "encryption failed"), strings.Contains(m, "decryption failed"):
		return "CRYPTO"
	default:
		return "ERR"
	}
}

func parseResp3Response(raw any) map[string]any {
	if raw == nil {
		return map[string]any{}
	}
	switch v := raw.(type) {
	case map[string]any:
		return v
	case string:
		var m map[string]any
		if json.Unmarshal([]byte(v), &m) == nil {
			return m
		}
		return map[string]any{"data": v}
	case int:
		return map[string]any{"value": v}
	default:
		return map[string]any{"data": v}
	}
}
"#
        .into(),
    }
}

fn gen_http() -> GeneratedFile {
    GeneratedFile {
        path: "http.go".into(),
        content: r#"// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// ErrPipelineNotSupported is returned by HttpTransport.ExecutePipeline because
// PIPELINE is a RESP3-only command. Use Resp3Transport or MoatResp3Transport
// to execute a server-side atomic pipeline.
var ErrPipelineNotSupported = errors.New("shroudb: PIPELINE is a RESP3-only command; use Resp3Transport or MoatResp3Transport")

// HttpTransport implements Transport via HTTP POST to a Moat gateway.
// Commands are sent as JSON to /v1/{engine}.
type HttpTransport struct {
	baseURL  string
	token    string
	client   *http.Client
	prefixes map[string]string
}

// NewHttpTransport creates an HTTP transport for the given Moat base URL.
func NewHttpTransport(baseURL string, token string, prefixes map[string]string) *HttpTransport {
	return &HttpTransport{
		baseURL:  strings.TrimRight(baseURL, "/"),
		token:    token,
		client:   &http.Client{},
		prefixes: prefixes,
	}
}

// Execute sends a command as an HTTP POST and returns the parsed response.
func (t *HttpTransport) Execute(ctx context.Context, engine string, args []string) (map[string]any, error) {
	prefix, ok := t.prefixes[engine]
	if !ok {
		prefix = fmt.Sprintf("/v1/%s", engine)
	}
	endpoint := t.baseURL + prefix

	body, err := json.Marshal(map[string]any{"args": args})
	if err != nil {
		return nil, fmt.Errorf("http: marshal: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("http: request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if t.token != "" {
		req.Header.Set("Authorization", "Bearer "+t.token)
	}

	resp, err := t.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("http: do: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("http: read body: %w", err)
	}

	if resp.StatusCode >= 400 {
		code := "INTERNAL"
		detail := string(respBody)
		var errResp map[string]any
		if json.Unmarshal(respBody, &errResp) == nil {
			if errMsg, ok := errResp["error"].(string); ok {
				parts := strings.SplitN(errMsg, " ", 2)
				code = parts[0]
				if len(parts) > 1 {
					detail = parts[1]
				} else {
					detail = errMsg
				}
			}
		}
		return nil, &ShrouDBError{Code: code, Message: detail}
	}

	var result map[string]any
	if err := json.Unmarshal(respBody, &result); err != nil {
		return nil, fmt.Errorf("http: unmarshal response: %w", err)
	}
	return result, nil
}

// ExecutePipeline always returns ErrPipelineNotSupported; PIPELINE requires RESP3.
func (t *HttpTransport) ExecutePipeline(ctx context.Context, engine string, commands [][]string, requestID string) ([]map[string]any, error) {
	return nil, ErrPipelineNotSupported
}

// Close is a no-op for HTTP transport (stateless).
func (t *HttpTransport) Close() error {
	return nil
}
"#
        .into(),
    }
}
