//! Per-engine response type struct generation for Go.

use crate::generator::GeneratedFile;
use crate::unified::ir::{EngineIR, FieldIR, UnifiedIR};
use heck::ToPascalCase;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_types(ir)]
}

fn gen_types(ir: &UnifiedIR) -> GeneratedFile {
    let mut out = String::new();
    out.push_str("// Auto-generated by shroudb-codegen. Do not edit.\n\n");
    out.push_str("package shroudb\n");

    for engine in &ir.engines {
        for cmd in &engine.commands {
            if cmd.response_fields.is_empty() {
                continue;
            }

            let type_name = format!(
                "{}{}Response",
                engine.name.to_pascal_case(),
                cmd.name.to_pascal_case()
            );

            writeln!(out).unwrap();
            writeln!(
                out,
                "// {type_name} is the response from {}.{}().",
                engine.name,
                cmd.name.to_pascal_case()
            )
            .unwrap();
            writeln!(out, "type {type_name} struct {{").unwrap();

            for field in &cmd.response_fields {
                let go_type = resolve_go_type(engine, &field.type_key);
                let json_tag = json_tag_for_field(field);
                let field_name = field.name.to_pascal_case();
                if !field.description.is_empty() {
                    writeln!(out, "\t// {} — {}", field_name, field.description).unwrap();
                }
                writeln!(out, "\t{field_name} {go_type} `json:\"{json_tag}\"`").unwrap();
            }

            out.push_str("}\n");
        }

        // Generate options structs for commands with named params.
        for cmd in &engine.commands {
            if cmd.named_params.is_empty() {
                continue;
            }

            let type_name = format!(
                "{}{}Options",
                engine.name.to_pascal_case(),
                cmd.name.to_pascal_case()
            );

            writeln!(out).unwrap();
            writeln!(
                out,
                "// {type_name} contains optional parameters for {}.{}().",
                engine.name,
                cmd.name.to_pascal_case()
            )
            .unwrap();
            writeln!(out, "type {type_name} struct {{").unwrap();

            for p in &cmd.named_params {
                let go_type = resolve_go_type(engine, &p.type_key);
                let ptr_type = pointer_type(&go_type, &p.type_key);
                let field_name = p.name.to_pascal_case();
                if !p.description.is_empty() {
                    writeln!(out, "\t// {} — {}", field_name, p.description).unwrap();
                }
                writeln!(
                    out,
                    "\t{field_name} {ptr_type} `json:\"{},omitempty\"`",
                    p.name
                )
                .unwrap();
            }

            out.push_str("}\n");
        }
    }

    GeneratedFile {
        path: "types.go".into(),
        content: out,
    }
}

/// Resolve the Go type for a given type key.
pub(crate) fn resolve_go_type(engine: &EngineIR, type_key: &str) -> String {
    // Check engine's defined types first.
    if let Some(t) = engine.types.get(type_key) {
        return t.go_type.clone();
    }
    // Built-in type mappings.
    match type_key {
        "string" | "keyring" | "plaintext" | "ciphertext" | "signature" => "string".into(),
        "integer" | "key_version" => "int".into(),
        "boolean" => "bool".into(),
        "json" => "any".into(),
        "map" => "map[string]any".into(),
        "array" => "[]any".into(),
        _ => "any".into(),
    }
}

/// For optional fields, wrap scalar types in a pointer.
fn pointer_type(go_type: &str, type_key: &str) -> String {
    match type_key {
        "boolean" => "bool".into(),
        "json" | "map" => go_type.into(),
        "array" => go_type.into(),
        _ => format!("*{go_type}"),
    }
}

fn json_tag_for_field(field: &FieldIR) -> String {
    if field.optional {
        format!("{},omitempty", field.name)
    } else {
        field.name.clone()
    }
}
