//! ShrouDB unified client class generation for Ruby.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use heck::{ToPascalCase, ToSnakeCase};
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_client(ir)]
}

fn gen_client(ir: &UnifiedIR) -> GeneratedFile {
    let gem = &ir.packages.ruby;
    let mut out = String::new();

    out.push_str("# frozen_string_literal: true\n");
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");

    out.push_str("module ShrouDB\n");
    out.push_str("  # Unified ShrouDB client.\n");
    out.push_str("  #\n");
    out.push_str("  # Provides namespaced access to all ShrouDB engines. Each engine is\n");
    out.push_str("  # accessible as a method (e.g., `db.cipher.encrypt(...)`).\n");
    out.push_str("  #\n");
    out.push_str("  # Supply a `moat` URL to route all engines through a Moat gateway,\n");
    out.push_str("  # or individual engine URIs for direct connections.\n");
    out.push_str("  class Client\n");

    // attr_reader for each engine namespace.
    for engine in &ir.engines {
        let snake = engine.name.to_snake_case();
        let pascal = engine.name.to_pascal_case();
        writeln!(
            out,
            "    # @return [{pascal}Namespace] {snake} engine namespace",
        )
        .unwrap();
        writeln!(out, "    attr_reader :{snake}").unwrap();
    }
    out.push('\n');

    // Constructor.
    out.push_str("    # Create a new ShrouDB client.\n");
    out.push_str("    #\n");
    out.push_str("    # @param moat [String, nil] Moat gateway URL (HTTP or RESP3)\n");
    out.push_str("    # @param token [String, nil] Bearer token for Moat HTTP authentication\n");
    for engine in &ir.engines {
        let snake = engine.name.to_snake_case();
        writeln!(
            out,
            "    # @param {snake} [String, nil] Direct {name} engine URI",
            name = engine.name
        )
        .unwrap();
    }

    // Build keyword arg list.
    let mut kwargs = vec!["moat: nil".to_string(), "token: nil".to_string()];
    for engine in &ir.engines {
        let snake = engine.name.to_snake_case();
        kwargs.push(format!("{snake}: nil"));
    }
    writeln!(out, "    def initialize({})", kwargs.join(", ")).unwrap();

    out.push_str("      @transports = []\n\n");

    // Resolve default transport from moat URI.
    out.push_str("      default_transport = nil\n");
    out.push_str("      if moat\n");
    out.push_str("        if moat.start_with?(\"http://\") || moat.start_with?(\"https://\")\n");
    out.push_str(
        "          default_transport = Transport::HttpTransport.new(moat, token: token)\n",
    );
    out.push_str("        else\n");
    out.push_str("          default_transport = Transport::MoatResp3Transport.new(moat)\n");
    out.push_str("        end\n");
    out.push_str("        @transports << default_transport\n");
    out.push_str("      end\n\n");

    // Per-engine transport resolution.
    for engine in &ir.engines {
        let snake = engine.name.to_snake_case();
        let pascal = engine.name.to_pascal_case();

        writeln!(out, "      if {snake}").unwrap();
        writeln!(out, "        t = Transport::Resp3Transport.new({snake})").unwrap();
        out.push_str("        @transports << t\n");
        writeln!(
            out,
            "        @{snake} = {pascal}Namespace.new(t, \"{name}\")",
            name = engine.name
        )
        .unwrap();
        out.push_str("      elsif default_transport\n");
        writeln!(
            out,
            "        @{snake} = {pascal}Namespace.new(default_transport, \"{name}\")",
            name = engine.name
        )
        .unwrap();
        out.push_str("      else\n");
        writeln!(out, "        @{snake} = nil").unwrap();
        out.push_str("      end\n\n");
    }

    out.push_str("    end\n\n");

    // close method.
    out.push_str("    # Close all connections and release resources.\n");
    out.push_str("    def close\n");
    out.push_str("      @transports.each(&:close)\n");
    out.push_str("    end\n");
    out.push_str("  end\n");
    out.push_str("end\n");

    GeneratedFile {
        path: format!("lib/{gem}/client.rb"),
        content: out,
    }
}
