//! Per-engine namespace class generation for Ruby.

use crate::generator::GeneratedFile;
use crate::unified::ir::{CommandIR, EngineIR, UnifiedIR};
use heck::{ToPascalCase, ToSnakeCase};
use std::fmt::Write;

use super::types::resolve_ruby_type;

fn rb_safe_name(name: &str) -> String {
    let snake = name.to_snake_case();
    match snake.as_str() {
        "new" => "new_value".into(),
        "old" => "old_value".into(),
        "class" => "klass".into(),
        "end" => "end_".into(),
        "begin" => "begin_".into(),
        "do" => "do_".into(),
        "def" => "def_".into(),
        "in" => "in_".into(),
        _ => snake,
    }
}

pub(super) fn generate(ir: &UnifiedIR, engine: &EngineIR) -> Vec<GeneratedFile> {
    vec![gen_engine_namespace(ir, engine)]
}

fn gen_engine_namespace(ir: &UnifiedIR, engine: &EngineIR) -> GeneratedFile {
    let gem = &ir.packages.ruby;
    let pascal = engine.name.to_pascal_case();
    let engine_snake = engine.name.to_snake_case();
    let mut out = String::new();

    out.push_str("# frozen_string_literal: true\n");
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");

    out.push_str("require \"base64\"\n\n");
    out.push_str("module ShrouDB\n");
    writeln!(out, "  # {pascal} — {}", engine.description).unwrap();
    writeln!(out, "  class {pascal}Namespace").unwrap();
    out.push_str("    # @api private\n");
    writeln!(
        out,
        "    def initialize(transport, engine = \"{name}\")",
        name = engine.name
    )
    .unwrap();
    out.push_str("      @transport = transport\n");
    out.push_str("      @engine = engine\n");
    out.push_str("    end\n");

    for cmd in &engine.commands {
        out.push('\n');
        gen_command_method(&mut out, engine, cmd);
    }

    out.push_str("  end\n");
    out.push_str("end\n");

    GeneratedFile {
        path: format!("lib/{gem}/engines/{engine_snake}.rb"),
        content: out,
    }
}

fn gen_command_method(out: &mut String, engine: &EngineIR, cmd: &CommandIR) {
    let method_name = cmd.name.to_snake_case();

    // Build parameter list.
    let mut params = Vec::new();
    for p in &cmd.positional_params {
        if p.required {
            params.push(rb_safe_name(&p.name));
        } else {
            params.push(format!("{} = nil", rb_safe_name(&p.name)));
        }
    }

    // Named params become keyword arguments.
    for p in &cmd.named_params {
        params.push(format!("{}: nil", rb_safe_name(&p.name)));
    }

    let param_str = params.join(", ");

    // YARD doc.
    let verb_display = match &cmd.subcommand {
        Some(sub) => format!("{} {}", cmd.verb, sub),
        None => cmd.verb.clone(),
    };
    writeln!(out, "    # {verb_display} — {}", cmd.description).unwrap();
    out.push_str("    #\n");

    for p in &cmd.positional_params {
        let ruby_type = if engine.is_base64_type(&p.type_key) {
            "String".to_string()
        } else {
            resolve_ruby_type(engine, &p.type_key)
        };
        let opt = if p.required { "" } else { ", nil" };
        writeln!(
            out,
            "    # @param {name} [{ruby_type}{opt}] {desc}",
            name = rb_safe_name(&p.name),
            desc = p.description
        )
        .unwrap();
    }
    for p in &cmd.named_params {
        let ruby_type = resolve_ruby_type(engine, &p.type_key);
        writeln!(
            out,
            "    # @param {name} [{ruby_type}, nil] {desc}",
            name = rb_safe_name(&p.name),
            desc = p.description
        )
        .unwrap();
    }

    // Return type.
    if !cmd.response_fields.is_empty() {
        let response_type = format!(
            "{engine}::{cmd}Response",
            engine = engine.name.to_pascal_case(),
            cmd = cmd.name.to_pascal_case()
        );
        writeln!(out, "    # @return [{response_type}]").unwrap();
    } else {
        out.push_str("    # @return [Hash]\n");
    }

    writeln!(out, "    def {method_name}({param_str})").unwrap();

    // Build the RESP3 args array.
    write!(out, "      args = [\"{verb}\"", verb = cmd.verb).unwrap();
    if let Some(sub) = &cmd.subcommand {
        write!(out, ", \"{sub}\"").unwrap();
    }
    out.push_str("]\n");

    // Append positional params.
    for p in &cmd.positional_params {
        let snake = rb_safe_name(&p.name);
        if p.required {
            if p.type_key == "json" {
                writeln!(
                    out,
                    "      args << ({snake}.is_a?(String) ? {snake} : JSON.generate({snake}))"
                )
                .unwrap();
            } else if engine.is_base64_type(&p.type_key) {
                // Auto-encode raw bytes to base64; pass strings through (assumed already encoded).
                writeln!(
                    out,
                    "      args << ({snake}.is_a?(String) ? {snake} : Base64.strict_encode64({snake}))"
                )
                .unwrap();
            } else {
                writeln!(out, "      args << {snake}.to_s").unwrap();
            }
        } else if p.type_key == "json" {
            writeln!(
                out,
                "      args << ({snake}.is_a?(String) ? {snake} : JSON.generate({snake})) unless {snake}.nil?"
            )
            .unwrap();
        } else if engine.is_base64_type(&p.type_key) {
            writeln!(
                out,
                "      args << ({snake}.is_a?(String) ? {snake} : Base64.strict_encode64({snake})) unless {snake}.nil?"
            )
            .unwrap();
        } else {
            writeln!(out, "      args << {snake}.to_s unless {snake}.nil?").unwrap();
        }
    }

    // Append named (keyword) params.
    for p in &cmd.named_params {
        let snake = rb_safe_name(&p.name);
        let default_key = p.name.to_uppercase();
        let wire_key = p.wire_key.as_deref().unwrap_or(&default_key);
        if p.type_key == "boolean" {
            writeln!(out, "      args << \"{wire_key}\" if {snake}").unwrap();
        } else if p.type_key == "json" {
            writeln!(
                out,
                "      unless {snake}.nil?\n        args << \"{wire_key}\"\n        args << ({snake}.is_a?(String) ? {snake} : JSON.generate({snake}))\n      end"
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "      unless {snake}.nil?\n        args << \"{wire_key}\"\n        args << {snake}.to_s\n      end"
            )
            .unwrap();
        }
    }

    // Execute and return.
    out.push_str("      raw = @transport.execute(@engine, args)\n");

    if !cmd.response_fields.is_empty() {
        let response_type = format!(
            "{engine}::{cmd}Response",
            engine = engine.name.to_pascal_case(),
            cmd = cmd.name.to_pascal_case()
        );
        let field_assignments: Vec<String> = cmd
            .response_fields
            .iter()
            .map(|f| {
                let snake = f.name.to_snake_case();
                let wire_name = &f.name;
                format!("{snake}: raw[\"{wire_name}\"]")
            })
            .collect();
        writeln!(
            out,
            "      {response_type}.new({fields})",
            fields = field_assignments.join(", ")
        )
        .unwrap();
    } else {
        out.push_str("      raw\n");
    }

    out.push_str("    end\n");
}
