//! Unified error hierarchy generation for Ruby.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use std::collections::BTreeMap;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_errors(ir)]
}

fn gen_errors(ir: &UnifiedIR) -> GeneratedFile {
    let gem = &ir.packages.ruby;

    // Merge all error codes across engines, deduplicating by code name.
    let mut all_codes: BTreeMap<String, (String, u16)> = BTreeMap::new();
    for engine in &ir.engines {
        for (code, def) in &engine.error_codes {
            all_codes
                .entry(code.clone())
                .or_insert_with(|| (def.description.clone(), def.http_equiv));
        }
    }

    let mut out = String::new();
    out.push_str("# frozen_string_literal: true\n");
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");

    out.push_str("module ShrouDB\n");

    // Error class.
    out.push_str("  # Base error class for all ShrouDB operations.\n");
    out.push_str("  class Error < StandardError\n");
    out.push_str(
        "    # @return [String] the error code from the server (e.g. \"NOTFOUND\", \"DENIED\")\n",
    );
    out.push_str("    attr_reader :code\n\n");
    out.push_str("    # @param code [String] server error code\n");
    out.push_str("    # @param message [String] human-readable detail\n");
    out.push_str("    def initialize(code, message)\n");
    out.push_str("      @code = code\n");
    out.push_str("      super(\"#{code} #{message}\")\n");
    out.push_str("    end\n");
    out.push_str("  end\n\n");

    // Error code constants module.
    out.push_str("  # Known ShrouDB error codes.\n");
    out.push_str("  module ErrorCode\n");
    for (code, (desc, _http)) in &all_codes {
        writeln!(out, "    # {desc}").unwrap();
        writeln!(out, "    {code} = \"{code}\"").unwrap();
    }
    out.push_str("  end\n\n");

    // Error code inference from engine messages.
    out.push_str("  # @api private\n");
    out.push_str("  def self._infer_error_code(message)\n");
    out.push_str("    m = message.to_s.downcase\n");
    out.push_str("    return \"NOTFOUND\" if m.include?(\"not found\")\n");
    out.push_str("    return \"EXISTS\" if m.include?(\"already exists\")\n");
    out.push_str(
        "    return \"DELETED\" if m.include?(\"is deleted\") || m.include?(\"soft-revoked\")\n",
    );
    out.push_str(
        "    return \"DENIED\" if m.include?(\"access denied\") || m.include?(\"policy denied\")\n",
    );
    out.push_str("    return \"VERIFICATION_FAILED\" if m.include?(\"verification failed\")\n");
    out.push_str("    return \"ACCOUNT_LOCKED\" if m.include?(\"account locked\")\n");
    out.push_str("    return \"INVALID_TOKEN\" if m.include?(\"invalid token\") || m.include?(\"token reuse\")\n");
    out.push_str("    return \"BADARG\" if m.include?(\"invalid argument\") || m.include?(\"invalid path\") || m.include?(\"unknown command\")\n");
    out.push_str("    return \"CAPABILITY_MISSING\" if m.include?(\"capability\") || m.include?(\"unavailable\")\n");
    out.push_str("    return \"RETIRED\" if m.include?(\"retired\")\n");
    out.push_str("    return \"DISABLED\" if m.include?(\"disabled\")\n");
    out.push_str(
        "    return \"SHREDDED\" if m.include?(\"shredded\") || m.include?(\"crypto-shred\")\n",
    );
    out.push_str("    return \"REVOKED\" if m.include?(\"revoked\")\n");
    out.push_str("    return \"CRYPTO\" if m.include?(\"encryption failed\") || m.include?(\"decryption failed\")\n");
    out.push_str("    \"ERR\"\n");
    out.push_str("  end\n");
    out.push_str("end\n");

    GeneratedFile {
        path: format!("lib/{gem}/errors.rb"),
        content: out,
    }
}
