//! Gemspec and top-level `lib/shroudb.rb` generation.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use heck::ToSnakeCase;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_gemspec(ir), gen_lib_entry(ir)]
}

fn gen_gemspec(ir: &UnifiedIR) -> GeneratedFile {
    let gem = &ir.packages.ruby;
    let version = &ir.version;

    let engine_list: Vec<_> = ir.engines.iter().map(|e| e.name.as_str()).collect();
    let desc = format!("ShrouDB unified SDK — {}", engine_list.join(", "));

    GeneratedFile {
        path: format!("{gem}.gemspec"),
        content: format!(
            r#"# frozen_string_literal: true
# Auto-generated by shroudb-codegen. Do not edit.

Gem::Specification.new do |s|
  s.name        = "{gem}"
  s.version     = "{version}"
  s.summary     = "{desc}"
  s.description = "Unified Ruby SDK for all ShrouDB security engines. "\
                  "Provides namespaced access with RESP3 and HTTP transport."
  s.license     = "MIT"
  s.authors     = ["ShrouDB"]
  s.homepage    = "https://github.com/shroudb/shroudb-sdk-ruby"

  s.required_ruby_version = ">= 3.1"

  s.files = Dir["lib/**/*.rb"]

  s.metadata = {{
    "source_code_uri" => "https://github.com/shroudb/shroudb-sdk-ruby",
    "github_repo" => "https://github.com/shroudb/shroudb-sdk-ruby",
    "rubygems_mfa_required" => "true"
  }}
end
"#
        ),
    }
}

fn gen_lib_entry(ir: &UnifiedIR) -> GeneratedFile {
    let gem = &ir.packages.ruby;
    let mut out = String::new();

    out.push_str("# frozen_string_literal: true\n");
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");

    // Require submodules.
    writeln!(out, "require_relative \"{gem}/errors\"").unwrap();
    writeln!(out, "require_relative \"{gem}/transport/interface\"").unwrap();
    writeln!(out, "require_relative \"{gem}/transport/resp3\"").unwrap();
    writeln!(out, "require_relative \"{gem}/transport/http\"").unwrap();

    for engine in &ir.engines {
        let snake = engine.name.to_snake_case();
        writeln!(out, "require_relative \"{gem}/types/{snake}\"").unwrap();
    }

    for engine in &ir.engines {
        let snake = engine.name.to_snake_case();
        writeln!(out, "require_relative \"{gem}/engines/{snake}\"").unwrap();
    }

    writeln!(out, "require_relative \"{gem}/client\"").unwrap();

    out.push_str("\n# Top-level ShrouDB module.\nmodule ShrouDB\nend\n");

    GeneratedFile {
        path: format!("lib/{gem}.rb"),
        content: out,
    }
}
