//! Transport interface, RESP3 codec, and HTTP transport generation for Ruby.

use crate::generator::GeneratedFile;
use crate::unified::ir::UnifiedIR;
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    vec![gen_interface(ir), gen_resp3(ir), gen_http(ir)]
}

fn gen_interface(ir: &UnifiedIR) -> GeneratedFile {
    let gem = &ir.packages.ruby;
    GeneratedFile {
        path: format!("lib/{gem}/transport/interface.rb"),
        content: r##"# frozen_string_literal: true
# Auto-generated by shroudb-codegen. Do not edit.

module ShrouDB
  module Transport
    # Base transport interface for ShrouDB engine communication.
    #
    # Implementations handle the wire format (RESP3 or HTTP) and connection
    # lifecycle. Engine namespace classes use this interface exclusively.
    class Interface
      # Execute a command and return the parsed response.
      #
      # @param engine [String] the engine name
      # @param args [Array<String>] command arguments
      # @return [Hash] parsed response
      def execute(engine, args)
        raise NotImplementedError, "#{self.class}#execute is not implemented"
      end

      # Execute N independent commands in one round-trip (client-side pipelining).
      #
      # Sends each command as a separate RESP3 frame on a single connection
      # and collects N responses in order. Unlike +execute_pipeline+, this is
      # **not** atomic — each command is independently dispatched, authorized,
      # and audited by the server.
      #
      # @param engine [String] the engine name
      # @param args_list [Array<Array<String>>] per-call args
      # @return [Array<Hash>] one parsed response per call
      def execute_many(engine, args_list)
        raise NotImplementedError, "#{self.class}#execute_many is not implemented"
      end

      # Execute a server-side atomic PIPELINE.
      #
      # Sends +PIPELINE+ with N nested sub-command arrays in a single RESP3
      # frame and returns one result per sub-command, in order. Pass
      # +request_id+ for idempotent retry — repeated calls with the same ID
      # return the cached result without re-executing.
      #
      # Only supported over RESP3; HTTP transports raise NotImplementedError.
      #
      # @param engine [String] the engine name
      # @param commands [Array<Array<String>>] sub-commands to execute
      # @param request_id [String, nil] optional idempotency key
      # @return [Array<Hash>] one parsed response per sub-command
      def execute_pipeline(engine, commands, request_id = nil)
        raise NotImplementedError, "#{self.class}#execute_pipeline is not implemented"
      end

      # Close all connections and release resources.
      def close
        # no-op by default
      end
    end
  end
end
"##
        .into(),
    }
}

fn gen_resp3(ir: &UnifiedIR) -> GeneratedFile {
    let gem = &ir.packages.ruby;
    let moat_port = ir.moat_resp3_port;
    GeneratedFile {
        path: format!("lib/{gem}/transport/resp3.rb"),
        content: format!(
            r##"# frozen_string_literal: true
# Auto-generated by shroudb-codegen. Do not edit.

require "socket"
require "openssl"
require "json"

module ShrouDB
  module Transport
    # Parse a ShrouDB RESP3 URI into connection parameters.
    def self.parse_uri(uri)
      m = uri.match(%r{{^([\w-]+)(\+tls)?://(?:([^@]+)@)?([^:/]+)(?::(\d+))?(?:/(.+))?$}})
      raise ArgumentError, "Invalid ShrouDB URI: #{{uri}}" unless m

      {{
        host: m[4],
        port: m[5] ? m[5].to_i : {moat_port},
        tls: m[2] == "+tls",
        token: m[3],
        keyspace: m[6]
      }}
    end

    # Low-level RESP3 connection.
    class Resp3Connection
      def initialize(host, port, tls: false)
        @sock = TCPSocket.new(host, port)
        if tls
          ctx = OpenSSL::SSL::SSLContext.new
          ctx.min_version = OpenSSL::SSL::TLS1_2_VERSION
          @sock = OpenSSL::SSL::SSLSocket.new(@sock, ctx)
          @sock.connect
        end
        @buffer = +""
      end

      def auth(token)
        execute("AUTH", token)
      end

      def execute(*args)
        write_command(args)
        read_response
      end

      # Write a PIPELINE frame: outer array of [prefix, REQUEST_ID?, ...nested sub-commands].
      def execute_pipeline_frame(prefix, commands, request_id)
        keyword_count = request_id ? 2 : 0
        outer_len = prefix.length + keyword_count + commands.length
        frame = "*#{{outer_len}}\r\n"
        prefix.each do |p|
          s = p.to_s
          frame << "$#{{s.bytesize}}\r\n#{{s}}\r\n"
        end
        if request_id
          frame << "$10\r\nREQUEST_ID\r\n"
          rid = request_id.to_s
          frame << "$#{{rid.bytesize}}\r\n#{{rid}}\r\n"
        end
        commands.each do |sub|
          frame << "*#{{sub.length}}\r\n"
          sub.each do |arg|
            s = arg.to_s
            frame << "$#{{s.bytesize}}\r\n#{{s}}\r\n"
          end
        end
        @sock.write(frame)
        read_response
      end

      def close
        @sock.close rescue nil
      end

      private

      def write_command(args)
        frame = "*#{{args.length}}\r\n"
        args.each do |arg|
          s = arg.to_s
          frame << "$#{{s.bytesize}}\r\n#{{s}}\r\n"
        end
        @sock.write(frame)
      end

      def read_response
        line = read_line
        tag = line[0]
        payload = line[1..]

        case tag
        when "+"  then payload
        when "-"
          parts = payload.split(" ", 2)
          code = parts[0] || "ERR"
          detail = parts[1] || payload
          code = ShrouDB._infer_error_code(detail) if code == "ERR"
          raise ShrouDB::Error.new(code, detail)
        when ":"  then payload.to_i
        when "$"
          len = payload.to_i
          return nil if len < 0
          data = read_bytes(len)
          read_bytes(2)
          data
        when "*"
          count = payload.to_i
          return nil if count < 0
          Array.new(count) {{ read_response }}
        when "%"
          count = payload.to_i
          result = {{}}
          count.times do
            key = read_response
            val = read_response
            result[key.to_s] = val
          end
          result
        else
          payload
        end
      end

      def read_line
        loop do
          idx = @buffer.index("\r\n")
          if idx
            line = @buffer[0...idx]
            @buffer = @buffer[(idx + 2)..]
            return line
          end
          @buffer << @sock.readpartial(4096)
        end
      end

      def read_bytes(n)
        while @buffer.bytesize < n
          @buffer << @sock.readpartial(4096)
        end
        data = @buffer[0, n]
        @buffer = @buffer[n..]
        data
      end
    end

    # Connection pool for RESP3 connections.
    class ConnectionPool
      def initialize(host, port, tls: false, max_size: 10, token: nil)
        @host = host
        @port = port
        @tls = tls
        @max_size = max_size
        @token = token
        @idle = []
        @active = 0
        @mutex = Mutex.new
        @cond = ConditionVariable.new
      end

      def with
        conn = acquire
        begin
          yield conn
        ensure
          release(conn)
        end
      end

      def close
        @mutex.synchronize do
          @idle.each(&:close)
          @idle.clear
        end
      end

      private

      def acquire
        @mutex.synchronize do
          loop do
            unless @idle.empty?
              @active += 1
              return @idle.pop
            end
            if @active < @max_size
              @active += 1
              conn = Resp3Connection.new(@host, @port, tls: @tls)
              conn.auth(@token) if @token
              return conn
            end
            @cond.wait(@mutex)
          end
        end
      end

      def release(conn)
        @mutex.synchronize do
          @active -= 1
          @idle.push(conn)
          @cond.signal
        end
      end
    end

    # RESP3 transport for direct engine connections.
    class Resp3Transport < Interface
      def initialize(uri)
        parsed = Transport.parse_uri(uri)
        @pool = ConnectionPool.new(parsed[:host], parsed[:port], tls: parsed[:tls], token: parsed[:token])
      end

      def execute(_engine, args)
        @pool.with do |conn|
          raw = conn.execute(*args)
          self.class.parse_response(raw)
        end
      end

      def execute_many(_engine, args_list)
        return [] if args_list.empty?
        @pool.with do |conn|
          args_list.map do |args|
            raw = conn.execute(*args)
            self.class.parse_response(raw)
          end
        end
      end

      def execute_pipeline(_engine, commands, request_id = nil)
        @pool.with do |conn|
          raw = conn.execute_pipeline_frame(["PIPELINE"], commands, request_id)
          raise ShrouDB::Error.new("ERR", "PIPELINE response was not an array") unless raw.is_a?(Array)
          raw.map {{ |item| self.class.parse_response(item) }}
        end
      end

      def close
        @pool.close
      end

      def self.parse_response(raw)
        case raw
        when nil    then {{}}
        when String
          begin
            parsed = JSON.parse(raw)
            parsed.is_a?(Hash) ? parsed : {{ "data" => raw }}
          rescue JSON::ParserError
            {{ "data" => raw }}
          end
        when Integer then {{ "value" => raw }}
        when Hash    then raw
        else              {{ "data" => raw }}
        end
      end
    end

    # RESP3 transport for Moat gateway (prefixes engine name).
    class MoatResp3Transport < Interface
      def initialize(uri)
        parsed = Transport.parse_uri(uri)
        @pool = ConnectionPool.new(parsed[:host], parsed[:port], tls: parsed[:tls], token: parsed[:token])
      end

      def execute(engine, args)
        prefixed = [engine.upcase, *args]
        @pool.with do |conn|
          raw = conn.execute(*prefixed)
          Resp3Transport.parse_response(raw)
        end
      end

      def execute_many(engine, args_list)
        return [] if args_list.empty?
        prefix = engine.upcase
        @pool.with do |conn|
          args_list.map do |args|
            raw = conn.execute(prefix, *args)
            Resp3Transport.parse_response(raw)
          end
        end
      end

      def execute_pipeline(engine, commands, request_id = nil)
        @pool.with do |conn|
          raw = conn.execute_pipeline_frame([engine.upcase, "PIPELINE"], commands, request_id)
          raise ShrouDB::Error.new("ERR", "PIPELINE response was not an array") unless raw.is_a?(Array)
          raw.map {{ |item| Resp3Transport.parse_response(item) }}
        end
      end

      def close
        @pool.close
      end
    end
  end
end
"##
        ),
    }
}

fn gen_http(ir: &UnifiedIR) -> GeneratedFile {
    let gem = &ir.packages.ruby;
    let mut prefixes_code = String::new();
    for engine in &ir.engines {
        writeln!(
            prefixes_code,
            "      \"{name}\" => \"{prefix}\",",
            name = engine.name,
            prefix = engine.http_prefix
        )
        .unwrap();
    }

    GeneratedFile {
        path: format!("lib/{gem}/transport/http.rb"),
        content: format!(
            r##"# frozen_string_literal: true
# Auto-generated by shroudb-codegen. Do not edit.

require "net/http"
require "uri"
require "json"

module ShrouDB
  module Transport
    DEFAULT_PREFIXES = {{
{prefixes_code}    }}.freeze

    # HTTP transport for Moat gateway connections.
    class HttpTransport < Interface
      def initialize(base_url, token: nil, prefixes: DEFAULT_PREFIXES)
        @base_url = base_url.chomp("/")
        @token = token
        @prefixes = prefixes
      end

      def execute_many(engine, args_list)
        # HTTP has no pipelining; fall back to sequential requests.
        args_list.map {{ |args| execute(engine, args) }}
      end

      def execute_pipeline(_engine, _commands, _request_id = nil)
        raise NotImplementedError,
              "PIPELINE is a RESP3-only command; use Resp3Transport or MoatResp3Transport"
      end

      def execute(engine, args)
        prefix = @prefixes.fetch(engine, "/v1/#{{engine}}")
        uri = URI.parse("#{{@base_url}}#{{prefix}}")

        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = uri.scheme == "https"

        request = Net::HTTP::Post.new(uri.request_uri)
        request["Content-Type"] = "application/json"
        request["Authorization"] = "Bearer #{{@token}}" if @token
        request.body = JSON.generate({{ "args" => args }})

        response = http.request(request)

        unless response.is_a?(Net::HTTPSuccess)
          code = "INTERNAL"
          detail = response.body
          begin
            json = JSON.parse(response.body)
            if json["error"]
              parts = json["error"].split(" ", 2)
              code = parts[0]
              detail = parts[1] || json["error"]
            end
          rescue JSON::ParserError; end
          raise ShrouDB::Error.new(code, detail)
        end

        JSON.parse(response.body)
      end

      def close; end
    end
  end
end
"##
        ),
    }
}
