//! Per-engine Ruby response type generation using Struct.

use crate::generator::GeneratedFile;
use crate::unified::ir::{EngineIR, UnifiedIR};
use heck::{ToPascalCase, ToSnakeCase};
use std::fmt::Write;

pub(super) fn generate(ir: &UnifiedIR) -> Vec<GeneratedFile> {
    ir.engines.iter().map(|e| gen_engine_types(ir, e)).collect()
}

fn gen_engine_types(ir: &UnifiedIR, engine: &EngineIR) -> GeneratedFile {
    let gem = &ir.packages.ruby;
    let engine_pascal = engine.name.to_pascal_case();
    let engine_snake = engine.name.to_snake_case();

    let mut out = String::new();
    out.push_str("# frozen_string_literal: true\n");
    out.push_str("# Auto-generated by shroudb-codegen. Do not edit.\n\n");

    out.push_str("module ShrouDB\n");
    writeln!(out, "  module {engine_pascal}").unwrap();

    for cmd in &engine.commands {
        if cmd.response_fields.is_empty() {
            continue;
        }

        let type_name = format!("{}Response", cmd.name.to_pascal_case());
        let cmd_snake = cmd.name.to_snake_case();

        let field_names: Vec<String> = cmd
            .response_fields
            .iter()
            .map(|f| format!(":{}", f.name.to_snake_case()))
            .collect();

        writeln!(out, "    # Response from {engine_pascal}#{cmd_snake}.").unwrap();
        for field in &cmd.response_fields {
            let ruby_type = resolve_ruby_type(engine, &field.type_key);
            let opt_suffix = if field.optional { ", nil" } else { "" };
            if !field.description.is_empty() {
                writeln!(
                    out,
                    "    # @!attribute [r] {}\n    #   @return [{ruby_type}{opt_suffix}] {}",
                    field.name.to_snake_case(),
                    field.description
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "    # @!attribute [r] {}\n    #   @return [{ruby_type}{opt_suffix}]",
                    field.name.to_snake_case()
                )
                .unwrap();
            }
        }

        writeln!(
            out,
            "    {type_name} = Struct.new({fields}, keyword_init: true)",
            fields = field_names.join(", ")
        )
        .unwrap();
        out.push('\n');
    }

    out.push_str("  end\n");
    out.push_str("end\n");

    GeneratedFile {
        path: format!("lib/{gem}/types/{engine_snake}.rb"),
        content: out,
    }
}

/// Resolve a type key to a Ruby type name.
pub(super) fn resolve_ruby_type(engine: &EngineIR, type_key: &str) -> String {
    // Check engine's defined types first.
    if let Some(t) = engine.types.get(type_key) {
        return t.ruby_type.clone();
    }
    // Built-in type mappings.
    match type_key {
        "string" | "keyring" | "plaintext" | "ciphertext" | "signature" | "token" => {
            "String".into()
        }
        "integer" | "key_version" => "Integer".into(),
        "boolean" => "Boolean".into(),
        "json" | "map" => "Hash".into(),
        "array" => "Array".into(),
        _ => "Object".into(),
    }
}
