name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: shroudb/.github/.github/workflows/rust-ci.yml@main
    with:
      deny: false
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
